docs/vision.md

Feedbacks welcome, there might be typos and things too long… it is a first try.

Second part — and end — of the vision page

---

docs/adapt-theme-to-brand.md

Still a WIP but here is what will the Adapt the theme to your brand will look like.
I heavily need Front Commerce Lite to have more content before finishing it.

[WIP] Adapt the theme to your brand

---

docs/extend-graphql-schema.md

Here it is!
I am not very proud of the example used, and we could rewrite it if one has a better idea.

Initial documentation about extending the GraphQL schema

---

docs/create-a-ui-component.md
docs/getting-started.md

Also related to https://github.com/front-commerce/front-commerce-lite/issues/17

Storybook documentation

---

_config.yml
source/_posts/hello-world.md
source/_posts/our-reacticon.md
source/_posts/prototype-ecommerce-applications-with-front-commerce-lite.md
source/blog/index.md
source/index.md
theme/_config.yml
theme/layout/blog.ejs
theme/layout/index.ejs
theme/layout/page.ejs
theme/layout/partials/back-to-top.ejs
theme/layout/partials/blog/list.ejs
theme/layout/partials/header.ejs
theme/layout/post.ejs
theme/source/style/_global/nav.less
theme/source/style/_modules/home.less
theme/source/style/_theme/content.less
theme/source/style/_theme/layout.less

Adding back the blog to the documentation.
Please note that the blog posts need to be in `_posts`.

Add blog part to the documentation

---

source/docs/essentials/installation.md

as per https://gitlab.com/front-commerce/front-commerce/issues/41

Update configuration pages with env vars instead of servicesKey files

---

source/_posts/to-1.0-and-beyond.md

Preview available at: https://deploy-preview-44--elastic-austin-cf9d40.netlify.com/blog/2019/03/07/to-1.0-and-beyond/

Blogpost: To 1.0 and beyond!

---

_config.yml
source/docs/advanced/production-ready/media-middleware.md
source/docs/reference/scripts.md

See https://deploy-preview-51--elastic-austin-cf9d40.netlify.com/docs/reference/scripts.html for the main page.

Initial documentation for available scripts

---

source/docs/advanced/graphql/remote-schemas.md

in schema stitching
See https://gitlab.com/front-commerce/front-commerce/issues/196 for more context

Add a note about root Query type limitation

---

_config.yml
source/docs/advanced/production-ready/checklist-before-production.md

Add a wip page telling about Offline/Maintenance page - #63

---

source/docs/reference/environment-variables.md

See https://deploy-preview-68--elastic-austin-cf9d40.netlify.com/docs/reference/environment-variables.html#Debugging

Document the new `DEBUG` env var to turn debugging on

---

_config.yml
source/docs/reference/cli.md

It's actually really hard to document these. Here is a first step. I'll need to come back to it later with a fresher mind.

Document the different scripts available

---

_config.yml
source/docs/magento2/i18n.md
source/docs/magento2/overview.md

Here is the documentation related to https://gitlab.com/front-commerce/front-commerce/issues/218
Preview: https://deploy-preview-72--elastic-austin-cf9d40.netlify.com/docs/magento2/i18n.html

Initial version of i18n in a Magento2 context

---

_config.yml
source/docs/advanced/graphql/remote-schemas.md
source/docs/reference/environment-variables.md
source/docs/reference/graphql-context.md
source/docs/reference/graphql-module-definition.md

Pages previews:
- https://deploy-preview-77--elastic-austin-cf9d40.netlify.com/docs/reference/graphql-module-definition.html#linkContextBuilders-optional
- https://deploy-preview-77--elastic-austin-cf9d40.netlify.com/docs/reference/graphql-context.html
- https://deploy-preview-77--elastic-austin-cf9d40.netlify.com/docs/advanced/graphql/remote-schemas.html#Customize-remote-HTTP-requests

Initial documentation about stitching context transforms

---

source/_posts/release-1.0.0-beta.0.md
source/_posts/release-1.0.0-beta.3.md
source/docs/appendices/release-notes.md
source/docs/reference/configurations.md

Here is a draft of the release note with information about https://gitlab.com/front-commerce/front-commerce/merge_requests/110

Config in parent modules

---

source/_posts/release-1.0.0-beta.3.md
source/docs/appendices/migration-guides.md

Here is a very small migration guide for payments updates.
People needing to upgrade should contact us rather than trying this on their own.

Submit payment

---

source/_posts/release-1.0.0-beta.3.md

Add a few more details about WYSIWYG components and minor updates.
I've put the configuration below payment and wysiwyg because it seems to have less hype potential. 
* should we put the fact that one of our partner contributed more visible?
* should we make schema stitching improvements more visible?

Add more details about Front-Commerce's latest release

---

source/docs/reference/configurations.md

Explain how the headers work when one needs to use the Client's IP.

Add a deeper explanation about how to configure a the client IP

---

_config.yml
source/docs/advanced/graphql/rate-limiting.md
source/docs/reference/configurations.md

Related to https://gitlab.com/front-commerce/front-commerce/issues/266

Add Rate Limiting documentation pages

---

source/_posts/introducing-cms-demos.md
source/_posts/release-1.0.0-beta.3.md
theme/source/style/_modules/home.less

Preview: https://deploy-preview-94--elastic-austin-cf9d40.netlify.com/blog/2019/11/20/introducing-cms-demos/

Draft of demos announcement

---

_config.yml
config/_config.yml
source/_posts/release-1.0.0-alpha.2.md
source/_posts/release-1.0.0-beta.0.md
source/_posts/release-1.0.0-beta.3.md
source/_posts/shutting-front-commerce-lite-down.md
source/docs/appendices/roadmap.md
source/docs/essentials/extend-the-graphql-schema.md
source/help.md

Here is a blog post to publish to announce that we are shutting down FCL.

Blog post: Shutting down fcl

---

_config.yml
source/docs/advanced/performance/faster-server-side-rendering.md
source/docs/advanced/performance/server-timings.md
source/docs/advanced/theme/server-side-rendering.md
source/docs/reference/environment-variables.md

There is a link to the yet to be finalized Configuration page, we must be careful about not breaking it when merging the other PR.

Document SSR and related mechanisms in place

---

source/_posts/front-commerce-2.0-rc.1-ecommerce-web-performance-for-humans.md
source/_posts/release-2.0.0-rc.1.md
source/docs/advanced/checkout/overview.md
source/docs/advanced/graphql/overview.md
source/docs/advanced/performance/overview.md
source/docs/advanced/production-ready/overview.md
source/docs/advanced/server/overview.md
source/docs/advanced/theme/overview.md
source/docs/advanced/theme/server-side-rendering.md
source/docs/appendices/migration-guides.md
source/docs/essentials/installation.md
source/docs/magento2/overview.md
source/docs/reference/environment-variables.md
source/docs/reference/graphql-module-definition.md
theme/source/style/_util/normalize.import.less

Adding migration guide for 2.0.0-rc.1

2.0.0 rc.1

---

source/docs/reference/environment-variables.md

add a note about a convenient env var that helps troubleshooting

---

source/docs/advanced/production-ready/multistore.md
source/docs/appendices/migration-guides.md
source/docs/appendices/troubleshooting.md
source/docs/reference/environment-variables.md

Here is the documentation for the changes incoming in the 2.0.0-rc.2.

2.0.0-rc.2

---

source/docs/appendices/migration-guides.md

deprecations
in the 2.0.0 version

Document backward incompatible changes from dependencies upgrade and

---

_config.yml
source/docs/advanced/payments/affirm.md
source/docs/advanced/payments/magento2-headless-payments.md
source/docs/advanced/payments/overview.md

I also reordered payment methods so they are in an alphabetical order

Document Affirm for Magento2 as a payment method

---

_config.yml
source/docs/advanced/payments/adyen.md

Document Adyen payment configuration (developer preview)

---

source/docs/advanced/theme/analytics.md

Add documentation for always enabled analytics integrations

---

_config.yml
source/docs/advanced/payments/buybox.md
source/docs/advanced/payments/overview.md

This PR adds information about how to use this Front-Commerce Payment.
Preview: https://deploy-preview-149--heuristic-almeida-1a1f35.netlify.app/docs/advanced/payments/buybox.html

Document BuyBox integration (2.3.0)

---

source/docs/appendices/release-notes.md

This is a simple update to our releases pages that allows me to quickly test CF pages integration

Latest patch releases (test Cloudflare pages)

---

_config.yml
source/docs/advanced/shipping/add-new-shipping-data-in-graphql.md
source/docs/advanced/shipping/colissimo.md
source/docs/advanced/shipping/custom-shipping-information.md
source/docs/advanced/shipping/mondial-relay.md
source/docs/advanced/shipping/overview.md
source/docs/appendices/migration-guides.md

This is a very early draft, but will be useful for the first integrations.

First draft for the shipping documentation

---

source/docs/magento1/installation.md

https://deploy-preview-158--heuristic-almeida-1a1f35.netlify.app/docs/magento1/installation.html#Install-with-composer

Simplify composer based Magento1 setup

---

source/_posts/front-commerce-2.5.md

Some grammatical\sentence structure edits

Minor changes

---

source/docs/advanced/theme/analytics.md

Hey :wave:
I'll be merging this doc directly, but I'd appreciate any feedback and will deal with them afterward.

Analytics custom integration

---

source/docs/appendices/migration-guides.md

added a section to migration guide mentioning the need to add a new icon

2.6.0 share wishlist

---

source/docs/advanced/server/configurations.md
source/docs/appendices/migration-guides.md
source/docs/magento1/search-engine.md
source/docs/reference/environment-variables.md

Document the Algolia's remote configuration + the config provider `fetchRemoteConfiguration` optional method.

2.6: Algolia remote config

---

source/docs/appendices/migration-guides.md
source/docs/appendices/release-notes.md

Migration guide + doc about Node.js minimum version

2.6: Node minimum version

---

source/docs/magento1/installation.md

this problem behind the recent support issue…

doc: Magento1 setup requires Add Store Code to Urls to be disabled

---

source/docs/appendices/migration-guides.md

This MR documents the removal from https://gitlab.com/front-commerce/front-commerce/-/merge_requests/525

Document the abandoned pact removal

---

source/docs/advanced/payments/payzen.md
source/docs/advanced/theme/layouts.md
source/docs/appendices/migration-guides.md
source/docs/reference/environment-variables.md
source/docs/reference/front-commerce-prepare.md

This PR officially documents the Lyra Collect support, along with the migration steps needed for existing Payzen embedded users to ensure they are up-to-date with correct urls now used.

Lyra Collect support

---

_config.yml
source/docs/prismic/index.md
source/docs/prismic/installation.md
source/docs/prismic/setup.md

It reflects the current state of the module (without going into too much details as a lots of changes are planned)

doc: Initialized Prismic related documentation

---

source/docs/appendices/migration-guides.md

This PR documents the change from https://gitlab.com/front-commerce/front-commerce/-/merge_requests/544 in the migration guide, for information.

Document EXIF image rotation support

---

source/docs/prismic/installation.md

* Fix setup for the new module layout (and add the Magento1 version)
* Add a note on the webhook purpose

Update the Prismic module configuration

---

source/docs/advanced/performance/faster-server-side-rendering.md
source/docs/advanced/performance/preloading-routes.md
source/docs/appendices/migration-guides.md
source/docs/reference/environment-variables.md

This document the removal introduced in https://gitlab.com/front-commerce/front-commerce/-/merge_requests/548

Document `FRONT_COMMERCE_FAST` removal

---

source/docs/advanced/features/smart-forms.md

and fixes some typos and typography issues

useEmailServerValidation documentation

---

source/docs/advanced/features/smart-forms.md
source/docs/reference/environment-variables.md

This PR improves the SmartForms documentation related to supporting implementations and Capency specifically.
It contains the latest configurations needed to configure the integration.

Update Capency documentation with the latest features

---

source/docs/advanced/production-ready/media-middleware.md

Implemented in https://gitlab.com/front-commerce/front-commerce/-/merge_requests/578

Documentation of proxy media files without resizing eg

---

source/docs/advanced/features/feature-flags.md

added documentation for enabling/disabling a feature using feature flags

feat: added feature flag docs

---

source/_posts/front-commerce-2.6.md
source/docs/advanced/performance/cache-control-and-cdn.md

As per https://gitlab.com/front-commerce/front-commerce/-/merge_requests/617

Fix the header name: s-max-age -> s-maxage

---

source/docs/advanced/theme/server-side-rendering.md
source/docs/appendices/migration-guides.md

This MR documents the change brought in https://gitlab.com/front-commerce/front-commerce/-/merge_requests/623

 Document SSR pages restriction from 2.8

---

_config.yml
source/docs/advanced/performance/deactivating-unnecessary-features.md
source/docs/advanced/performance/overview.md
source/docs/appendices/migration-guides.md
source/docs/reference/environment-variables.md

Feature introduced in https://gitlab.com/front-commerce/front-commerce/-/merge_requests/615

Document how to disable server response compression

---

source/docs/advanced/features/smart-forms.md

* fixed some typos
* make a bit clearer that without smart-forms-capency module, there's a very limited implementation

Smart forms doc improvements

---

source/docs/magento1/search-engine.md

Improve algolias documentation

---

_config.yml
source/docs/advanced/graphql/change-resolver-behavior.md
source/docs/advanced/graphql/overview.md

Document how to properly change the behavior of a resolver

---

source/docs/appendices/migration-guides.md

Related to https://gitlab.com/front-commerce/front-commerce/-/merge_requests/631

Document how to fix / as division deprecation sass warnings

---

source/docs/prismic/installation.md

using cURL as it's a bit more common than httpie

Document how to refresh the prismic ref without restarting FC

---

source/docs/appendices/migration-guides.md

See https://gitlab.com/front-commerce/front-commerce/-/merge_requests/622

Document custom options extraCost update

---

source/docs/advanced/production-ready/logging.md
source/docs/appendices/migration-guides.md

accross the documentation and in the migration guide
See https://gitlab.com/front-commerce/front-commerce/-/merge_requests/633

Document the new Payment dedicated logger

---

source/docs/advanced/theme/route-dispatcher.md
source/docs/prismic/routable-types.md

the documentation for the dispatcher was out of date and not documenting the registerUrlMarcher from loaders.Page

update dispatcher url matcher docs

---

source/docs/advanced/features/display-a-map.md

Typo choose not chose

---

source/docs/concepts/architecture-overview.md
source/docs/essentials/create-a-ui-component.md

Fixes some minor typos and sentences.

fix: fixes a typos

---

source/docs/appendices/migration-guides.md

https://deploy-preview-251--heuristic-almeida-1a1f35.netlify.app/docs/appendices/migration-guides.html#Zoom-in-on-product-images

Migration guide for zoom in product image feature

---

_config.yml
source/docs/advanced/payments/overview.md
source/docs/advanced/payments/payment-on-account.md
source/docs/appendices/migration-guides.md
source/docs/magento2/advanced.md
source/docs/magento2/b2b.md
source/docs/magento2/headless-payments.md
source/docs/magento2/overview.md

2 new pages:
* https://deploy-preview-259--heuristic-almeida-1a1f35.netlify.app/docs/magento2/b2b.html
* https://deploy-preview-259--heuristic-almeida-1a1f35.netlify.app/docs/advanced/payments/payment-on-account.html

Document how to set up B2B module and Payment on account

---

_config.yml
source/_posts/front-commerce-2.11.md
source/blog/index.md
source/index.md
theme/layout/blog.ejs
theme/layout/post.ejs

Preview available in: https://deploy-preview-263--heuristic-almeida-1a1f35.netlify.app/blog/2021/11/24/front-commerce-2.11/

2 11 release post

---

source/docs/appendices/release-notes.md

https://deploy-preview-266--heuristic-almeida-1a1f35.netlify.app/docs/appendices/release-notes.html

Add release dates in release notes

---

source/docs/appendices/release-notes.md

https://deploy-preview-265--heuristic-almeida-1a1f35.netlify.app/docs/appendices/release-notes.html

Release note for 2.11.0

---

source/docs/appendices/migration-guides.md

This PR adds a note I forgot to MR/Merge yesterday about updating the codebase to the latest prettier version.
Feel free to merge/amend/reword it so it can be shipped as soon as possible.

Added a note about the Prettier update

---

source/docs/appendices/migration-guides.md

added to migration guid mention about default value if cookieMaxAgeInMonths

cookieMaxAgeInMonths to migration guide

---

source/docs/advanced/production-ready/media-middleware.md
source/docs/appendices/migration-guides.md

Documentation for https://gitlab.com/front-commerce/front-commerce/-/merge_requests/876

Image extensions check

---

source/docs/magento2/page-builder.md

Adds structured page builder content types

---

source/docs/magento2/b2b.md

https://deploy-preview-283--heuristic-almeida-1a1f35.netlify.app/docs/magento2/b2b.html

Magento2 Commerce module requirement for B2B

---

source/docs/advanced/payments/adyen.md

fix: wrong component file name in Adyen documentation

---

source/docs/appendices/migration-guides.md

Documented parts related to my work

Fc 776 requisition list documentation

---

_config.yml
source/docs/magento2/b2b.md
source/docs/magento2/commerce.md

https://deploy-preview-290--heuristic-almeida-1a1f35.netlify.app/docs/magento2/commerce.html

Document the Magento2 commerce and Cms Page children feature

---

_config.yml
source/docs/magento2/search-engine.md

https://deploy-preview-297--heuristic-almeida-1a1f35.netlify.app/docs/magento2/search-engine.html

Document requirements and setup for M2 search

---

source/docs/appendices/migration-guides.md
source/docs/magento1/search-engine.md
source/docs/magento2/search-engine.md

Related to https://gitlab.com/front-commerce/front-commerce/-/merge_requests/981
Main changes visible in:
* https://deploy-preview-303--heuristic-almeida-1a1f35.netlify.app/docs/magento2/search-engine.html#Algolia
* https://deploy-preview-303--heuristic-almeida-1a1f35.netlify.app/docs/appendices/migration-guides.html#2-12-0-gt-2-13-0

Document Magento2 + Algolia setup

---

.editorconfig
.husky/pre-commit
.prettierrc
package-lock.json
package.json

If a developer has plugins installed it might change the syntax/formatting, this ensures that the formatting is standardized, avoiding unnecessary changes in a pull request.
https://user-images.githubusercontent.com/39598117/150960545-c05be5de-62b7-4f07-8486-02f55d06bd62.mov

feat(dx): add prettier support

---

source/docs/advanced/payments/hipay.md

Documentation related to : https://gitlab.com/front-commerce/front-commerce/-/merge_requests/1033#note_840216011

Fc 732 hipay customdata

---

source/docs/appendices/release-process.md

This MR improves the "Release process" page with details about our cycles and the 2022 calendar so integrators and customers can anticipate our releases.
Preview: https://deploy-preview-329--heuristic-almeida-1a1f35.netlify.app/docs/appendices/release-process.html
_This content was authored by Josquin_

Communicate more detail about our release pace

---

source/docs/advanced/features/display-a-map.md
source/docs/advanced/payments/paypal.md
source/docs/advanced/payments/payzen.md
source/docs/advanced/theme/analytics.md
source/docs/appendices/migration-guides.md

Those changes weren't mean to be in production yet.

Reverted last documentation changes about CSP removal

---

source/docs/advanced/features/display-a-map.md
source/docs/advanced/payments/paypal.md
source/docs/advanced/payments/payzen.md
source/docs/advanced/theme/analytics.md
source/docs/appendices/migration-guides.md

Copycat of #334, which as been mistakenly merged to `main` instead of `next`.

chore(configuration): Updated documentation upon removal of default CSPs in Front-Commerce

---

source/docs/magento2/commerce.md

fixed missing commands from the documentation page

fix(m2-commerce): installation instructions

---

source/docs/appendices/migration-guides.md

Documentation for https://gitlab.com/front-commerce/front-commerce/-/merge_requests/967 see https://gitlab.com/front-commerce/front-commerce/-/merge_requests/967#note_848282658

Add a note in migration guide about some dead code removal

---

source/docs/reference/environment-variables.md

Introduced into https://gitlab.com/front-commerce/front-commerce/-/merge_requests/1117

Document `front-commerce:graphql` debug flag

---

source/docs/prismic/routable-types.md

Related to questions from integrators and also in a previous MR https://github.com/front-commerce/developers.front-commerce.com/pull/362#discussion_r832319216

chore(prismic): add advanced content relationship examples

---

source/docs/advanced/theme/route-dispatcher.md
source/docs/appendices/migration-guides.md

This PR documents the feature added by https://gitlab.com/front-commerce/front-commerce/-/merge_requests/1148
Preview: https://deploy-preview-368--heuristic-almeida-1a1f35.netlify.app/docs/appendices/migration-guides.html#New-features-in-2-14-0

Document support for variables in custom routes

---

source/docs/advanced/production-ready/logging.md
source/docs/advanced/production-ready/sessions.md

Improve the configuration to provide simple configurations for logging and sessions based on the environment variable for the CloudV2

cloud-v2: configuration tips for deployments

---

source/docs/advanced/features/advanced-external-logins.md
source/docs/advanced/performance/cache-control-and-cdn.md
source/docs/essentials/extend-the-graphql-schema.md
source/docs/prismic/routable-types.md

If not why not? https://github.com/front-commerce/developers.front-commerce.com/pull/377#discussion_r848534596 😁 happy to see I'm not 'the the' only one

chore: fix 'the the' grammar

---

_config.yml
source/docs/reference/debugging.md
source/docs/reference/environment-variables.md
theme/source/style/_common-post.less
theme/source/style/_global/video.less

Adds a guide for node debug in front-commerce-skeleton using vscode or chrome devtools
Preview: https://deploy-preview-377--heuristic-almeida-1a1f35.netlify.app/docs/reference/debugging.html
https://user-images.githubusercontent.com/39598117/162025005-36a22fb8-f6e5-4c7f-b3e4-16f27336c5bd.mp4
https://user-images.githubusercontent.com/39598117/162024726-6d247230-9d36-4b4f-a1c2-c6de433a4922.mp4

Add Node debugging guide

---

source/docs/advanced/theme/wysiwyg-platform.md

Due to prettier removing the indentation of code blocks between ordered lists, this causes the list to be formatted separately, resulting in a new list per list item.
https://deploy-preview-390--heuristic-almeida-1a1f35.netlify.app/docs/advanced/theme/wysiwyg-platform.html#Add-a-custom-Magento-Widget

chore: fix wysiwyg documentation formatting

---

source/docs/advanced/theme/analytics.md
source/docs/appendices/migration-guides.md

Some minor improvements to the analytics docs, this change will allow for more structured data in the sidebar.
https://deploy-preview-392--heuristic-almeida-1a1f35.netlify.app/docs/advanced/theme/analytics.html#Integrations

chore: improve analytics docs

---

source/docs/advanced/theme/wysiwyg.md

Related to this PR https://github.com/front-commerce/developers.front-commerce.com/pull/390. This fixes the Ordered List and improves the layout of the content.
https://deploy-preview-393--heuristic-almeida-1a1f35.netlify.app/docs/advanced/theme/wysiwyg.html

fix: fixes the formatting for wysiwyg ordered lists

---

source/docs/appendices/migration-guides.md
source/docs/appendices/release-notes.md

https://deploy-preview-404--heuristic-almeida-1a1f35.netlify.app/docs/appendices/migration-guides.html#New-features-in-2-15-0

2.15 has some features, let's advertise them a bit :)

---

source/docs/prismic/index.md

https://deploy-preview-405--heuristic-almeida-1a1f35.netlify.app/docs/prismic/

Add embed fields to prismic overview

---

source/docs/appendices/migration-guides.md

https://deploy-preview-426--heuristic-almeida-1a1f35.netlify.app/docs/appendices/migration-guides.html#2-15-0-gt-2-16-0

Migration guide 2.16

---

source/docs/advanced/production-ready/logging.md

see : https://deploy-preview-427--heuristic-almeida-1a1f35.netlify.app/docs/advanced/production-ready/logging.html

feat(logging): add custom type for custom transport

---

source/docs/advanced/payments/adyen.md
source/docs/appendices/migration-guides.md

Documentation for https://gitlab.com/front-commerce/front-commerce/-/merge_requests/1395

Remember my credit card feature with adyen 

---

docs/advanced/payments/payzen.mdx
docs/appendices/migration-guides/index.mdx

Migration guide: https://deploy-preview-433--heuristic-almeida-1a1f35.netlify.app/docs/appendices/migration-guides/#payment-workflow-rework
Payzen doc : https://deploy-preview-433--heuristic-almeida-1a1f35.netlify.app/docs/appendices/migration-guides/#payment-workflow-rework

Fc 275 lyra ipn

---

docs/advanced/payments/adyen.mdx
docs/appendices/migration-guides/index.mdx

[Adyen documentation](https://deploy-preview-440--heuristic-almeida-1a1f35.netlify.app/docs/advanced/payments/adyen)
[Migration Guide](https://deploy-preview-440--heuristic-almeida-1a1f35.netlify.app/docs/appendices/migration-guides/)

feat(adyen): Added documentation for Magento2 Adyen module version 8

---

docs/appendices/migration-guides/index.mdx

Document https://gitlab.com/front-commerce/front-commerce/-/merge_requests/1469
https://deploy-preview-462--heuristic-almeida-1a1f35.netlify.app/docs/appendices/migration-guides/#front_commerce_web_unsafe_use_deprecated_fields-support-removal

Document FRONT_COMMERCE_WEB_UNSAFE_USE_DEPRECATED_FIELDS support removal

---

docs/appendices/migration-guides/index.mdx

https://deploy-preview-461--heuristic-almeida-1a1f35.netlify.app/docs/appendices/migration-guides/#domainevent-implementations-reworked

refactor(payments): notify in migration guide

---

docs/appendices/migration-guides/index.mdx
docs/prismic/embed-fields.mdx
docs/prismic/expose-content.mdx
docs/prismic/installation.mdx
docs/prismic/resolver-cache.mdx

closes FC-837
Preview: https://deploy-preview-463--heuristic-almeida-1a1f35.netlify.app/docs/appendices/migration-guides/#the-prismic-module-has-moved-to-a-new-home

Update prismic module

---

docs/advanced/features/external-logins/advanced-external-logins.mdx
docs/advanced/features/external-logins/index.mdx

noticed while working on https://gitlab.com/front-commerce/front-commerce/-/merge_requests/1456

fix: various typos, consistent capitalization and working anchors in external login doc

---

docs/advanced/payments/adyen.mdx

Added / completed PayPal part to Adyen documentation.
https://deploy-preview-449--heuristic-almeida-1a1f35.netlify.app/docs/advanced/payments/adyen

docs(adyen/paypal): Updated Paypal with Adyen documentation to include CSP and Adyen documents links

---

docs/appendices/migration-guides/index.mdx

https://deploy-preview-472--heuristic-almeida-1a1f35.netlify.app/docs/appendices/migration-guides/#path-to-regexp-package-added

Document the required installation of path-to-regexp

---

docs/advanced/theme/wysiwyg/README.mdx

https://deploy-preview-467--heuristic-almeida-1a1f35.netlify.app/docs/advanced/theme/wysiwyg/#map-this-new-type-to-a-specific-react-component-that-will-apply-the-needed

chore(dx): add docs for appending new wysiwyg components

---

docs/advanced/payments/front-commerce-payments.mdx

2 minors fixes in FC payment page.
see https://deploy-preview-486--heuristic-almeida-1a1f35.netlify.app/docs/advanced/payments/front-commerce-payments
Currently:

Front-Commerce payment fixes

---

docs/advanced/payments/stripe.mdx
docs/appendices/migration-guides/index.mdx

https://deploy-preview-488--heuristic-almeida-1a1f35.netlify.app/docs/advanced/payments/stripe#advanced-disable-automatic-capture
https://deploy-preview-488--heuristic-almeida-1a1f35.netlify.app/docs/appendices/migration-guides/#2180---2190

Stripe: add a configuration to prevent automatic capture

---

docs/magento1/search-engine.mdx
docs/magento2/search-engine.mdx

Document how to add a facet in algolia
https://deploy-preview-485--heuristic-almeida-1a1f35.netlify.app/docs/magento2/search-engine#requirements-1

improve(algolia): document addition of algolia facets

---

docs/magento2/search-engine.mdx
docs/reference/environment-variables.mdx

Added documention on how to enable Attraqt datasource for Magento2.
- [Configuration](https://deploy-preview-491--heuristic-almeida-1a1f35.netlify.app/docs/magento2/search-engine#attraqt)
- [Environment variable](https://deploy-preview-491--heuristic-almeida-1a1f35.netlify.app/docs/reference/environment-variables#attraqt)

feat(attraqt): Added Attraqt documentation

---

docs/advanced/payments/payment-workflows-specificities.mdx

Document redirectBeforeOrder workflow implementation 
https://deploy-preview-490--heuristic-almeida-1a1f35.netlify.app/docs/advanced/payments/payment-workflows-specificities#redirect-before-order

feat(payments): document redirectBefore/AfterOrder workflows

---

docs/advanced/payments/payzen.mdx

fix: add `lyra` to imgSrc csp

---

docs/appendices/migration-guides/index.mdx
docs/magento2/advanced.mdx
docs/reference/environment-variables.mdx

https://deploy-preview-500--heuristic-almeida-1a1f35.netlify.app/docs/magento2/advanced#caching-customers-cart
https://deploy-preview-500--heuristic-almeida-1a1f35.netlify.app/docs/reference/environment-variables#cache

Document FRONT_COMMERCE_CART_CACHE_ENABLE and cart cache feature

---

docs/appendices/migration-guides/index.mdx
docs/essentials/adapt-theme-to-your-brand.mdx

documentation for this MR: https://gitlab.com/front-commerce/front-commerce/-/merge_requests/1428
https://deploy-preview-479--heuristic-almeida-1a1f35.netlify.app/docs/appendices/migration-guides/#2180---2190

chore: add custom icons migration guide

---

docs/reference/cli.mdx

Updated related issue: https://linear.app/front-commerce/issue/FC-1004/add-codemod-support-to-cli
Example: https://deploy-preview-255--heuristic-almeida-1a1f35.netlify.app/docs/reference/cli#front-commerce-codemod

feat(cli): adds codemod documentation (FC-1004)

---

docs/advanced/production-ready/media-middleware.mdx

https://deploy-preview-501--heuristic-almeida-1a1f35.netlify.app/docs/advanced/production-ready/media-middleware#ignore-caching-for-builded-files

feat(express): document the new FRONT_COMMERCE_BACKEND_IGNORE_CACHE_REGEX variable

---

docs/appendices/migration-guides/index.mdx

https://deploy-preview-506--heuristic-almeida-1a1f35.netlify.app/docs/appendices/migration-guides/#default-country-from-graph

 Added documentation for Country's isDefault

---

docs/advanced/features/maintenance-mode.mdx

https://deploy-preview-508--heuristic-almeida-1a1f35.netlify.app/docs/advanced/features/maintenance-mode

fix: recommend IPv6 usage in maintenance whitelist

---

docs/advanced/shipping/chronorelais.mdx
docs/advanced/shipping/custom-shipping-information.mdx
docs/appendices/migration-guides/index.mdx
docs/reference/environment-variables.mdx

https://deploy-preview-509--heuristic-almeida-1a1f35.netlify.app/docs/advanced/shipping/chronorelais
https://deploy-preview-509--heuristic-almeida-1a1f35.netlify.app/docs/appendices/migration-guides/#formitem-inline-property-depreciation

Document the ChronoRelais module installation + a minor depreciation

---

docs/appendices/migration-guides/index.mdx

https://deploy-preview-511--heuristic-almeida-1a1f35.netlify.app/docs/appendices/migration-guides/#replaced-mkdirp-package-with-make-dir

chore: mkdirp migration

---

docs/magento2/search-engine.mdx

https://deploy-preview-514--heuristic-almeida-1a1f35.netlify.app/docs/magento2/search-engine#facets

Added documentation for Attraqt Facets

---

changelog/front-commerce-2.18.mdx
changelog/front-commerce-2.19.mdx
docs/appendices/release-notes.mdx

Previews:
- https://deploy-preview-518--heuristic-almeida-1a1f35.netlify.app/changelog/front-commerce-2.19
- https://deploy-preview-518--heuristic-almeida-1a1f35.netlify.app/docs/appendices/release-notes#2190-2022-10-27

feat: add 2.19 release changelog entry

---

src/css/custom.css

fix(styling): fixes overflow in markdown 😳

---

docs/advanced/analytics/plugins.mdx

https://deploy-preview-524--heuristic-almeida-1a1f35.netlify.app/docs/advanced/analytics/plugins#matomo

Added link to Matomo example in the docs.

---

src/components/Homepage/Hero.tsx

| Before | After |
|--------|-------|
|  ![image](https://user-images.githubusercontent.com/39598117/199920642-0bde8082-9f09-47fd-9013-093d4bb13bb8.png) | ![image](https://user-images.githubusercontent.com/39598117/199920781-2f5d3d5d-6831-4b2a-a1f8-c180bae97d74.png) |

fix(styling): fixes partner logos in light mode

---

docs/welcome.mdx

remove duplicate text

---

docs/advanced/payments/payzen.mdx

to ensure customers get a more efficient support from Lyra
These information are advices I got from today's call with a support person that could help us troubleshooting an issue efficiently.
Our goal in the future would be to access this support team more easily without multiple back and forth.
**Preview:** https://lyra-support-tips--heuristic-almeida-1a1f35.netlify.app/docs/advanced/payments/payzen#contacting-lyras-support

Document contact information for Lyra support

---

changelog/authors.yml
changelog/front-commerce-2.11.mdx
changelog/front-commerce-2.12.mdx
changelog/front-commerce-2.13.mdx
changelog/front-commerce-2.14.mdx
changelog/front-commerce-2.15.mdx
changelog/front-commerce-2.17.mdx
changelog/front-commerce-2.18.mdx
changelog/front-commerce-2.19.mdx
docs/appendices/release-notes.mdx
src/components/Calendly.tsx

- [/changelog/front-commerce-2.11](https://deploy-preview-533--heuristic-almeida-1a1f35.netlify.app/changelog/front-commerce-2.11)
- [/changelog/front-commerce-2.12](https://deploy-preview-533--heuristic-almeida-1a1f35.netlify.app/changelog/front-commerce-2.12)
- [/changelog/front-commerce-2.13](https://deploy-preview-533--heuristic-almeida-1a1f35.netlify.app/changelog/front-commerce-2.13)
- [/changelog/front-commerce-2.14](https://deploy-preview-533--heuristic-almeida-1a1f35.netlify.app/changelog/front-commerce-2.14)
- [/changelog/front-commerce-2.15](https://deploy-preview-533--heuristic-almeida-1a1f35.netlify.app/changelog/front-commerce-2.15)
- [/changelog/front-commerce-2.17](https://deploy-preview-533--heuristic-almeida-1a1f35.netlify.app/changelog/front-commerce-2.17)
- …

refactor: change related contact points

---

docs/reference/configurations.mdx

https://deploy-preview-547--heuristic-almeida-1a1f35.netlify.app/docs/reference/configurations#configimagesjs

chore: add images config docs

---

docs/advanced/features/display-a-map.mdx
docs/essentials/create-a-business-component.mdx

Related to : https://gitlab.blackswift.cloud/front-commerce/front-commerce/-/merge_requests/1586
Preview Page: https://deploy-preview-523--heuristic-almeida-1a1f35.netlify.app/docs/advanced/features/display-a-map#open-street-map-osm-with-leaflet

chore(deps): update react-leaflet

---

docs/advanced/performance/assets-cdn-domain.mdx
docs/advanced/performance/cache-control-and-cdn.mdx
docs/advanced/performance/preloading-routes.mdx
docs/advanced/theme/server-side-rendering.mdx
docs/magento2/advanced.mdx
docs/magento2/b2b.mdx
docs/magento2/commerce.mdx
docs/magento2/detect-admin-users.mdx
docs/magento2/log-as-customer.mdx
docs/magento2/page-builder.mdx
docs/magento2/search-engine.mdx
docs/reference/environment-variables.mdx
docs/reference/graphql-module-definition.mdx
docs/reference/wishlist-provider.mdx

This PR improves !551 by:
- removing extra `;` added there
- replacing new occurrences of such mentions with a different wording

Improve <SinceVersion /> usage

---

docs/advanced/images-adapters/_category_.yml
docs/advanced/images-adapters/cloudinary.mdx
docs/advanced/images-adapters/custom-adapter.mdx

* https://deploy-preview-550--heuristic-almeida-1a1f35.netlify.app/docs/advanced/images-adapters/cloudinary
* https://deploy-preview-550--heuristic-almeida-1a1f35.netlify.app/docs/advanced/images-adapters/custom-adapter

ImageAdapter - Cloudinary

---

docs/appendices/release-notes.mdx

[Release notes](https://deploy-preview-548--heuristic-almeida-1a1f35.netlify.app/docs/appendices/release-notes#latest-version)

Add node 18 compatibility

---

changelog/front-commerce-2.20.mdx
docs/appendices/release-notes.mdx

For information (review already made internally)

Release: add the 2.20 announcement

---

docs/appendices/migration-guides/index.mdx

https://deploy-preview-563--heuristic-almeida-1a1f35.netlify.app/docs/appendices/migration-guides/#path-to-regexp-package-added

Add a note about the path-to-regexp migration step

---

docs/appendices/release-notes.mdx

to match what was done in https://gitlab.blackswift.cloud/front-commerce/front-commerce/-/merge_requests/1774
https://deploy-preview-564--heuristic-almeida-1a1f35.netlify.app/docs/appendices/release-notes
Note: done against `main` because even if the current version does not have the change provided by the MR mentioned above, this requirement is still valid (especially node 14.17+)

Update require Node.js version to match FC requirements

---

docs/advanced/images-adapters/cloudinary.mdx

Improves the readability of the code syntax.

chore: improve code syntax

---

docs/magento1/installation.mdx

Noticed in the side bar of https://developers.front-commerce.com/docs/magento1/installation#configuration

fix: remove bold on sub title

---

docs/advanced/images-adapters/twicpics.mdx

https://deploy-preview-555--heuristic-almeida-1a1f35.netlify.app/docs/advanced/images-adapters/twicpics

ImageAdapter - TwicPics

---

docs/advanced/features/feature-flags.mdx
docs/appendices/migration-guides/archives.mdx
docs/appendices/migration-guides/index.mdx
docs/essentials/add-component-to-storybook.mdx
docs/magento1/installation.mdx

minor fixes I have locally for quite some time

Minor fixes (typo, spelling mistake)

---

docs/magento2/detect-admin-users.mdx

Some strange importing happening in this example 😝
https://deploy-preview-581--heuristic-almeida-1a1f35.netlify.app/docs/magento2/detect-admin-users#your-initial-graphql-module

fix: admin data loader

---

docs/advanced/payments/adyen.mdx

Also added steps in order to enable  Google Pay.
The supported list features Alipay and ApplePay as well, that's under the condition Adyen support successfully helps us with the issue we have before the end of the cycle.

FC-1340 FC-1342 feat(adyen): added supported list of payment methods

---

docs/advanced/server/file-uploads.mdx

https://deploy-preview-610--heuristic-almeida-1a1f35.netlify.app/docs/advanced/server/file-upload

Document how to implement file upload

---

docs/advanced/features/return-merchandise-authorization.mdx

* M1EE is not the only supported platform
* spelling mistake

Fixes in RMA page

---

docs/magento2/advanced.mdx

related to https://gitlab.blackswift.cloud/front-commerce/front-commerce/-/merge_requests/1829
https://deploy-preview-612--heuristic-almeida-1a1f35.netlify.app/docs/magento2/advanced

Add a warning CartCache usage

---

docs/reference/environment-variables.mdx

https://deploy-preview-614--heuristic-almeida-1a1f35.netlify.app/docs/reference/environment-variables#debugging

fix: update available debug flag list

---

docs/magento2/add-question-on-registration.mdx

resolves: https://app.intercom.com/a/inbox/ehgzoeah/inbox/team/5209928/conversation/188350900000710?view=List

chore: add m2 page description

---

docs/migration/manual-migration.mdx

https://deploy-preview-622--heuristic-almeida-1a1f35.netlify.app/docs/remixed/migration/manual-migration#sass-migration

chore: add sass manual migration step

---

docs/migration/manual-migration.mdx

https://deploy-preview-623--heuristic-almeida-1a1f35.netlify.app/docs/remixed/migration/manual-migration#modal-routes

chore: add modal route manual migration

---

versioned_docs/version-2.x/magento2/search-engine.mdx
versioned_docs/version-2.x/reference/environment-variables.mdx

This PR documents the configuration added in [this MR](https://gitlab.blackswift.cloud/front-commerce/front-commerce/-/merge_requests/1909)
**[Preview ↗](https://deploy-preview-626--heuristic-almeida-1a1f35.netlify.app//docs/2.x/reference/environment-variables#attraqt)**

Document the new `FRONT_COMMERCE_ATTRAQT_DISABLED` environment variable

---

versioned_docs/version-2.x/magento2/b2b.mdx

To keep the same notice that is being removed in https://gitlab.blackswift.cloud/front-commerce/magento2-b2b-module-front-commerce/-/merge_requests/2

 Add the version recommendation from M2 B2B readme

---

versioned_docs/version-2.x/magento2/commerce.mdx

To keep the same notice that is being removed in https://gitlab.blackswift.cloud/front-commerce/magento2-commerce-module-front-commerce/-/merge_requests/22

Add the version recommendation from M2 commerce readme

---

versioned_docs/version-2.x/magento1/advanced.mdx
versioned_docs/version-2.x/magento2/advanced.mdx

This PR documents https://github.com/front-commerce/examples/pull/2 for more discoverability in our docs.
Preview:
- [for Magento2](https://deploy-preview-638--heuristic-almeida-1a1f35.netlify.app/docs/2.x/magento2/advanced#additional-headers-in-magento-api-calls)
- [for Magento1](https://deploy-preview-638--heuristic-almeida-1a1f35.netlify.app/docs/2.x/magento1/advanced#additional-headers-in-magento-api-calls)

Document Quanta example for Magento extra headers

---

versioned_docs/version-2.x/essentials/installation.mdx
versioned_docs/version-2.x/magento2/graphql.mdx
versioned_docs/version-2.x/magento2/installation.mdx
versioned_docs/version-2.x/reference/environment-variables.mdx

Related to:
* https://gitlab.blackswift.cloud/front-commerce/magento2-module-front-commerce/-/merge_requests/138
* https://gitlab.blackswift.cloud/front-commerce/front-commerce/-/merge_requests/1941
* https://gitlab.blackswift.cloud/front-commerce/front-commerce-skeleton/-/merge_requests/61
Preview of the changed/created pages/sections:
* https://deploy-preview-637--heuristic-almeida-1a1f35.netlify.app/docs/2.x/essentials/installation
* https://deploy-preview-637--heuristic-almeida-1a1f35.netlify.app/docs/2.x/magento2/installation
* https://deploy-preview-637--heuristic-almeida-1a1f35.netlify.app/docs/2.x/reference/environment-variables#magento-1

Improve installation documentation

---

docs/migration/deprecated-code-removal.mdx

https://deploy-preview-642--heuristic-almeida-1a1f35.netlify.app/docs/remixed/migration/deprecated-code-removal#theme-components

chore: document link prop removal

---

docs/migration/deprecated-code-removal.mdx

https://deploy-preview-641--heuristic-almeida-1a1f35.netlify.app/docs/remixed/migration/deprecated-code-removal#wysiwygv1

chore: document legacy wysiwyg removal

---

versioned_docs/version-2.x/advanced/production-ready/sessions.mdx

Version 7 does not seem compatible with our stack ~~(WIP on understanding why)~~
it looks like we have a too old version of the redis package and updating it is not trivial as well.

fix: make sure to install version 6 of connect-redis

---

blog/vscode-remote-development-setup-and-usage.mdx

Avoids having the full blogpost in the blog list ([preview](https://deploy-preview-653--heuristic-almeida-1a1f35.netlify.app/blog))
https://user-images.githubusercontent.com/39598117/237022785-cb3f5840-4301-41f0-bdc8-daf5e7c75c3d.mp4

fix: blog post truncation

---

versioned_docs/version-2.x/advanced/images-adapters/akamai-image-manager.mdx

There's not much to document here, although I kind of feel like I'm missing something.

Akamai  Image Manager adapter documentation

---

versioned_docs/version-2.x/appendices/migration-guides/index.mdx
versioned_docs/version-2.x/reference/content-security-policy.mdx

- https://gitlab.blackswift.cloud/front-commerce/front-commerce/-/merge_requests/2033
- https://app.intercom.com/a/inbox/ehgzoeah/inbox/admin/5309138/conversation/188350900000787?view=List

CSP Directives

---

changelog/front-commerce-2.19.mdx

Reported in: https://app.intercom.com/a/inbox/ehgzoeah/inbox/team/5209928/conversation/188350900000804?view=List

Update Analytics examples URL

---

versioned_docs/version-2.x/advanced/analytics/plugins.mdx

Everything is in the diff!
[**➡️ Preview**](https://deploy-preview-672--heuristic-almeida-1a1f35.netlify.app//docs/2.x/advanced/analytics/plugins#google-analytics-4)
_Thanks @Aerowiel for reporting this._

Fix incorrect GA configuration example

---

versioned_docs/version-2.x/appendices/migration-guides/index.mdx

This migration adds instruction on how to display enhanced multi shipping if override has been done on components

feat(magento2-multi-shipping): add documentation about migration

---

versioned_docs/version-2.x/magic-button/x-ray.mdx

see https://gitlab.blackswift.cloud/front-commerce/front-commerce/-/merge_requests/2101

chore(StorefrontContent): add custom sources override documentation

---

versioned_docs/version-2.x/appendices/migration-guides/index.mdx

* removed a duplicated line
* style more robust (see https://gitlab.blackswift.cloud/front-commerce/front-commerce/-/merge_requests/2095)
* chunk optimization (see https://gitlab.blackswift.cloud/front-commerce/front-commerce/-/merge_requests/2098)

Migration guide changes related to late Magic Button improvements

---

versioned_docs/version-2.x/advanced/features/maintenance-mode.mdx

Attempt to improve the documentation on maintenance mode

refactor: improve maintenance mode API documentation

---

versioned_docs/version-2.x/magic-button/x-ray.mdx
versioned_docs/version-2.x/reference/environment-variables.mdx

Adding documentation about the env variable `FRONT_COMMERCE_MAGENTO_TYPE` for using xray with Magento 1

Fc 1461 x ray magento1

---

versioned_docs/version-2.x/appendices/migration-guides/index.mdx

Mark `_colors.scss` override as mandatory

fix(magic-button): mark color override as mandatory

---

versioned_docs/version-2.x/appendices/migration-guides/index.mdx
versioned_docs/version-2.x/appendices/release-notes.mdx

Update documentation for dropped Node14 support

docs: update minimal node version

---

versioned_docs/version-2.x/appendices/migration-guides/index.mdx

See [related MR](https://gitlab.blackswift.cloud/front-commerce/front-commerce/-/merge_requests/2121).

Documented canonical url computation changes

---

versioned_docs/version-2.x/appendices/migration-guides/index.mdx

This PR documents https://gitlab.blackswift.cloud/front-commerce/front-commerce/-/merge_requests/2120 in the migration guide.
Preview: https://deploy-preview-697--heuristic-almeida-1a1f35.netlify.app/docs/2.x/appendices/migration-guides/#performance-remove-chunks-preloading

Document chunks scripts preloading removal

---

versioned_docs/version-2.x/appendices/migration-guides/index.mdx

https://deploy-preview-708--heuristic-almeida-1a1f35.netlify.app/docs/2.x/appendices/migration-guides/#requisition-list-uid-update

docs(requisition-list): migration guide for uid value

---

versioned_docs/version-2.x/advanced/checkout/temporary-shipping-address.mdx

Adding documentation about temporary shipping address for negotiable quote
[New section](https://deploy-preview-705--heuristic-almeida-1a1f35.netlify.app/docs/2.x/advanced/checkout/temporary-shipping-address#nagociable-quote-checkout)

Fc 1454 negotiable quote temp shipping address

---

docs/migration/manual-migration.mdx

Related to changes done in https://gitlab.blackswift.cloud/front-commerce/front-commerce/-/merge_requests/2216
https://deploy-preview-719--heuristic-almeida-1a1f35.netlify.app/docs/remixed/migration/manual-migration#calculations

Document manual fixes in stylesheets after running codemods

---

versioned_docs/version-2.x/advanced/checkout/temporary-shipping-address.mdx

Typo fixes identified by @Kagaminara and forgotten in this [MR](https://github.com/front-commerce/developers.front-commerce.com/pull/705)

typo(checkout): fix typo

---

blog/audits-conducted-in-front-commerce-for-client-projects.mdx

Preview: https://deploy-preview-728--heuristic-almeida-1a1f35.netlify.app/blog/audits-conducted-in-front-commerce-for-client-projects

chore: august blog post

---

changelog/front-commerce-2.26.mdx
versioned_docs/version-2.x/appendices/migration-guides/index.mdx
versioned_docs/version-2.x/appendices/release-notes.mdx

This PR contains the changes related to the 2.26 release.
- [**Announcement**](https://deploy-preview-729--heuristic-almeida-1a1f35.netlify.app/changelog/front-commerce-2.26)

Release 2.26

---

docs/migration/manual-migration.mdx

This MR introduce Enhancer removal for enhancer used only for data loading
https://deploy-preview-731--heuristic-almeida-1a1f35.netlify.app/docs/remixed/migration/manual-migration#enhancers-components

feat(migration): enhancers removal

---

docs/migration/manual-migration.mdx

Related MR: https://gitlab.blackswift.cloud/front-commerce/front-commerce/-/merge_requests/2354
[Preview](https://deploy-preview-734--heuristic-almeida-1a1f35.netlify.app/docs/remixed/migration/manual-migration)

Documented withEntityNotFound api change

---

docs/migration/manual-migration.mdx

This PR follows [this cleanup MR](https://gitlab.blackswift.cloud/front-commerce/front-commerce/-/merge_requests/2373) and documents breaking changes and enhancements brought by FC-1591.
[Preview](https://deploy-preview-737--heuristic-almeida-1a1f35.netlify.app/docs/remixed/migration/manual-migration#breaking-partialproductquery-removal)

Document PDP breaking changes and enhancements

---

docs/api-reference/front-commerce-remix/index.mdx

https://gitlab.blackswift.cloud/front-commerce/front-commerce/-/merge_requests/2369
- https://deploy-preview-740--heuristic-almeida-1a1f35.netlify.app/docs/remixed/api-reference/front-commerce-remix/#improved-loader-data-types

chore: document typed loader data

---

versioned_docs/version-2.x/magento1/exposing-additional-attributes.mdx

examples are invalid, this fixes them.

fix: invalid XML example in exposing-additional-attributes.mdx

---

docs/migration/manual-migration.mdx

This documents the change introduced in: https://gitlab.blackswift.cloud/front-commerce/front-commerce/-/merge_requests/2456

chore: document SmartLayout removal

---

docs/migration/manual-migration.mdx

This PR documents the removal of `EnhanceAddressBook`.
Related MRs 
- https://gitlab.blackswift.cloud/front-commerce/front-commerce/-/merge_requests/2439
- https://gitlab.blackswift.cloud/front-commerce/front-commerce/-/merge_requests/2444

Document Account page enhancer removal

---

docs/migration/manual-migration.mdx

See https://gitlab.blackswift.cloud/front-commerce/front-commerce/-/merge_requests/2495

Document CartSeo and react-helmet-async removal

---

docs/api-reference/front-commerce-remix/generate-metas.mdx
docs/migration/manual-migration.mdx

and fix typos and minor typography mistakes

Client side log removal and generateMetas import change

---

docs/04-api-reference/front-commerce-core/create-resized-image-response.mdx

fixes a const name `ONE_YEAR` -> `ONE_WEEK`

chore: fix const name

---

docs/04-api-reference/front-commerce-core/create-resized-image-response.mdx
docs/04-api-reference/front-commerce-remix/front-commerce-app.mdx
docs/04-api-reference/front-commerce-remix/index.mdx

It updates references for remix v2 and also slightly improves the existing docs

chore: update remix v2 references

---

changelog/front-commerce-3.0.mdx

This PR adds the 3.0 announcement to our changelog.
**[Preview](https://deploy-preview-773--heuristic-almeida-1a1f35.netlify.app/changelog/front-commerce-3.0)**

Release announcement: 3.0

---

docs/04-api-reference/front-commerce-remix/index.mdx

🤫 fixes merge conflict which was not resolved.

chore: fix merge conflict

---

docs/01-get-started/your-first-route.mdx

This PR is a quick and easy guide made for integrator to create a basic route that renders static content and uses a basic loader.
Preview: https://deploy-preview-769--heuristic-almeida-1a1f35.netlify.app/docs/remixed/get-started/your-first-route
**note:** _Note sure how much to add in it for now, that's open to discussion :)_

Getting's started: First route 

---

docs/02-guides/extend-the-graphql-schema.mdx
docs/02-guides/register-an-extension.mdx

https://deploy-preview-776--heuristic-almeida-1a1f35.netlify.app/docs/remixed/guides/register-an-extension
https://deploy-preview-776--heuristic-almeida-1a1f35.netlify.app/docs/remixed/guides/extend-the-graphql-schema

Document how to register an extension and how to extend the Graph

---

docs/03-extensions/theme-chocolatine/reference/css-variables.mdx

This MR aims to list all variables currently used in the theme Chocolatine and provide a quick brief on what they are and should be used for.
I'm wide open to suggestion about phrasing, as design is not my _forte_. Also, I'm not sure how deep in the variables usage it would be interesting / useful to go.
Note: A lot more variables than what is present in this list are _exported_ in the theme. However, only the variables _used_ in the theme are documented.
---
**[Preview](https://deploy-preview-775--heuristic-almeida-1a1f35.netlify.app/docs/remixed/extensions/theme-chocolatine/reference/css-variables)**

Theme Chocolatine: Document css variables

---

docs/04-api-reference/front-commerce-core/key-values.mdx

This MR adds documentation for keyValues methods
**[Preview](https://deploy-preview-784--heuristic-almeida-1a1f35.netlify.app/docs/remixed/api-reference/front-commerce-core/key-values)**

doc: keyvalues

---

docs/migration/compat-mode.mdx
docs/migration/deprecated-code-removal.mdx
docs/migration/features-removal.mdx

This PR documents the feature removal from https://gitlab.blackswift.cloud/front-commerce/front-commerce/-/merge_requests/2624
- [Features removal](https://deploy-preview-787--heuristic-almeida-1a1f35.netlify.app/docs/remixed/migration/features-removal) (new page)
- [Deprecated code - new section](https://deploy-preview-787--heuristic-almeida-1a1f35.netlify.app/docs/remixed/migration/deprecated-code-removal#features)

Document GraphQL rate limiting removal

---

docs/02-guides/override-a-component.mdx

This MR is about extending a component from theme-chocolatine.
I've based myself on V2 documentation and adapted it to new folder organization
https://deploy-preview-770--heuristic-almeida-1a1f35.netlify.app/docs/remixed/guides/override-a-component

doc: component override basic conversion

---

docs/04-api-reference/front-commerce-core/react.mdx

This MR add documentation for the `@front-commerce/core/react` public API
https://deploy-preview-778--heuristic-almeida-1a1f35.netlify.app/docs/remixed/api-reference/front-commerce-core/react

docs: React core documentation

---

docs/02-guides/configuration.mdx
docs/03-extensions/algolia/_category_.yml
docs/03-extensions/algolia/how-to/_category_.yml
docs/03-extensions/algolia/how-to/magento1.mdx
docs/03-extensions/algolia/how-to/magento2.mdx
docs/03-extensions/algolia/how-to/standalone.mdx
docs/03-extensions/algolia/index.mdx
docs/03-extensions/algolia/reference/_category_.yml
docs/03-extensions/algolia/reference/environment-variables.mdx

Preview: https://deploy-preview-791--heuristic-almeida-1a1f35.netlify.app/docs/remixed/extensions/algolia/
~~Note: https://github.com/front-commerce/developers.front-commerce.com/pull/791/files#diff-db834843913aab24eb3b13f07c68e0bb5760b88a31aa72f6ce1516d55caf8c9dR52-R57 is commented out because the feature has not been implemented yet.~~ Wrong assumptions

Document Algolia extension

---

docs/02-guides/extend-the-graphql-schema.mdx
docs/04-api-reference/front-commerce-core/defineExtension.mdx

This documents the changes introduced in https://gitlab.blackswift.cloud/front-commerce/front-commerce/-/merge_requests/2736

chore: document extension definition schema

---

docs/03-extensions/magento2/reference/axios-instances.mdx

Documents the axois apis for magento2, see https://gitlab.blackswift.cloud/front-commerce/front-commerce/-/merge_requests/2734

chore: document makeUserClientFromRequest and makeCartUrlBuilderFromRequest

---

versioned_docs/version-2.x/magento1/installation.mdx

This MR documents how to enable facet sorting in Magento 1.
Related changes: https://gitlab.blackswift.cloud/front-commerce/front-commerce/-/merge_requests/2766

Sort facets in Magento1

---

docs/migration/layered-navigation.mdx

See https://gitlab.blackswift.cloud/front-commerce/front-commerce/-/merge_requests/2750#note_107744
https://deploy-preview-802--heuristic-almeida-1a1f35.netlify.app/docs/remixed/migration/layered-navigation

Document heavy changes in Layer navigation

---

docs/01-get-started/installation.mdx

This PR fixes some details and instructions so that following a minimal install works out of the box.

Fix installation instructions (as of 3.1.0-alpha.3)

---

docs/01-get-started/installation.mdx
docs/03-extensions/algolia/_category_.yml
docs/03-extensions/contentful/_category_.yml
docs/03-extensions/magento1/_category_.yaml
docs/03-extensions/magento1/how-to/_category_.yml
docs/03-extensions/magento1/how-to/setup-magento-extension.mdx
docs/03-extensions/magento1/how-to/setup-magento-module.mdx
docs/03-extensions/magento1/index.mdx
docs/03-extensions/magento2/index.mdx

This MR implements documentation for Magento 1 Setup

Fc 1861 minimal initial magento1 extension

---

docs/03-extensions/theme-chocolatine/reference/css-variables.mdx

This MR documents the changes made here: [!2902](https://gitlab.blackswift.cloud/front-commerce/front-commerce/-/merge_requests/2902).

Documented script to check for unused CSS custom properties

---

docs/04-api-reference/front-commerce-remix/index.mdx
docs/100-upgrade/migration-guides/3.0-3.1.mdx
docs/migration/automated-migration.mdx

Documents the migration CLI
- [migration/automated-migration](https://deploy-preview-826--heuristic-almeida-1a1f35.netlify.app/docs/3.x/migration/automated-migration)
- [api-reference/front-commerce-remix/#migrate](https://deploy-preview-826--heuristic-almeida-1a1f35.netlify.app/docs/3.x/api-reference/front-commerce-remix/#migrate)
- [upgrade/migration-guides/3.0-3.1#automated-migration](https://deploy-preview-826--heuristic-almeida-1a1f35.netlify.app/docs/3.x/upgrade/migration-guides/3.0-3.1#automated-migration)

chore: document migrate CLI

---

docs/01-get-started/loading-data-from-unified-graphql-schema.mdx

This documents how to load dta rom unified GraphQL schema.
- https://gitlab.blackswift.cloud/front-commerce/front-commerce/-/merge_requests/2944
- https://deploy-preview-798--heuristic-almeida-1a1f35.netlify.app/docs/remixed/get-started/loading-data-from-unified-graphql-schema

chore: Loading data from unified GraphQL schema

---

docs/02-guides/configuration/01-add-a-configuration-provider.mdx

We recently introduced a token to secure the debug endpoint, see https://gitlab.blackswift.cloud/front-commerce/front-commerce/-/merge_requests/3032

chore: document debug endpoint security update

---

docs/02-guides/server-side-events/create-an-event.mdx
docs/04-api-reference/front-commerce-core/ServerEvent.mdx

This MR introduce documentation on how to create and use an event emitter
https://deploy-preview-847--heuristic-almeida-1a1f35.netlify.app/docs/3.x/guides/server-side-events/create-an-event

doc(server-side-events): create event emitter

---

versioned_docs/version-2.x/advanced/theme/prevent-scroll-to-top.mdx

This explain how to disable auto scroll to top when navigating

feat(theme): add scrollToTop automatic documentation

---

docs/100-upgrade/migration-guides/3.3-3.4.mdx

Documents process of updating mixed graphql modules and meta modules.
https://deploy-preview-856--heuristic-almeida-1a1f35.netlify.app/docs/3.x/upgrade/migration-guides/3.3-3.4#removal-of-meta-modules

chore: document migration of mixed graphql modules and meta modules

---

docs/02-guides/server-side-events/create-an-event.mdx

This PR is a followup PR for nit asked to be fixed

fix(server-event): follow up fixs

---

docs/100-upgrade/migration-guides/3.3-3.4.mdx

This MR documents the changes from [!3254](https://gitlab.blackswift.cloud/front-commerce/front-commerce/-/merge_requests/3254) in the migration guide.
Preview (TBD)

Document fixes related to a crash in configuration modal

---

docs/100-upgrade/migration-guides/3.3-3.4.mdx

This MR documents further changes made on requisition-list related files.
[Preview ](https://deploy-preview-865--heuristic-almeida-1a1f35.netlify.app/docs/3.x/upgrade/migration-guides/3.3-3.4#requisition-list-related-theme-changes)

docs: Documented changes mades for requisition list fixes

---

versioned_docs/version-2.x/advanced/production-ready/logging.mdx

Hello :wave:
I've noticed this small typo in the 2.x docs.
Take care :hugs:

Fix client logger import example for client

---

docs/04-api-reference/front-commerce-remix/index.mdx

This MR document the addition of `useApiFetcherPromise` in https://gitlab.blackswift.cloud/front-commerce/front-commerce/-/merge_requests/3294/diffs?commit_id=bc572e0cdb7790c915889c699f951afb997750ab.

docs: Document useApiFetcherPromise

---

versioned_docs/version-2.x/reference/environment-variables.mdx

This MR documents the rolling session feature configuration.
It also adds the `FRONT_COMMERCE_COOKIE_MAX_AGE_IN_MS` documentation that wasn't mentioned anywhere in the documentation.
Preview (tbd).

FC-2168 Documented session rolling configuration

---

docs/100-upgrade/migration-guides/3.3-3.4.mdx

This MR documents the migration step to correctly add Storybooks from FC 3.3 to 3.4.
[Preview](https://deploy-preview-883--heuristic-almeida-1a1f35.netlify.app/docs/3.x/upgrade/migration-guides/3.3-3.4#storybook)

FC-2260: Documented Storybook migration guide

---

docs/100-upgrade/migration-guides/3.3-3.4.mdx

This MR follows a code change in https://gitlab.blackswift.cloud/front-commerce/front-commerce/-/merge_requests/3330 that updated the command to build the styleguide.

docs: Fix the styleguide build commands after code update

---

docs/02-guides/maintenance-mode.mdx

This MR introduces a first batch of documentation related to the maintenance mode usage and configuration.
Note that this documentation will have to evolve along with the maintenance mode feature. Since there isn't much to say about it right now, I condensed the information in a single page.
[Preview](https://deploy-preview-884--heuristic-almeida-1a1f35.netlify.app/docs/3.x/guides/maintenance-mode)

docs: Documented maintenance mode usage and customization

---

docs/04-api-reference/front-commerce-remix/front-commerce-app.mdx
docs/100-upgrade/migration-guides/3.3-3.4.mdx

This add methods related to flash message in documentation

docs(remix): adding flash messages related method

---

docs/100-upgrade/migration-guides/3.3-3.4.mdx

Minor updates to migration guide

chore: update migration guide documentation

---

docs/02-guides/extend-the-graphql-schema.mdx
docs/03-extensions/contentful/how-to/add-content-types.mdx
docs/03-extensions/contentful/how-to/add-x-ray-compatibility.mdx
docs/03-extensions/contentful/how-to/configure-preview-mode.mdx
docs/03-extensions/magento1/reference/axios-instances.mdx
docs/03-extensions/magento1/reference/store-config-loader.mdx
docs/03-extensions/magento2/reference/axios-instances.mdx

This documents all the updates for `GraphqlModule` and `GraphqlRuntime` changes

chore: update all GraphqlModule and GraphqlRuntime docs

---

changelog/front-commerce-3.4-2.29.mdx

chore: improve release notes

---

docs/100-upgrade/troubleshooting/index.mdx

Adds a troubleshooting section, and documents the HMR style loss

chore: document troubleshooting for hmr styles loss

---

versioned_docs/version-2.x/appendices/migration-guides/index.mdx

This adds documentation about the quick order component update

docs(quick-order): add migration guide for quick order component

---

docs/03-extensions/twicpics/index.mdx

This implements documentation for TwicPics module for Front-Commerce V3

docs(twicpics): adding twicpics documentation

---

docs/02-guides/extend-the-graphql-schema.mdx
docs/04-api-reference/front-commerce-core/graphql.mdx
docs/100-upgrade/migration-guides/3.5-3.6.mdx

This documents the API to implement custom scalars in a graphql module.

Add custom scalars to GraphQL module

---

docs/03-extensions/payzen/how-to/magento2.mdx
docs/03-extensions/payzen/index.mdx
versioned_docs/version-2.x/advanced/payments/payzen.mdx

This add documentation for usage of Payzen with Magento2 Module

Fc 2082 3x payzen as a magento2 payment

---

docs/02-guides/flash-messages.mdx
docs/100-upgrade/migration-guides/3.5-3.6.mdx

This add a simple documentation about flash message migration

docs(flash-messages): implement small flash message documentation

---

docs/03-extensions/gezy/reference/environment-variables.mdx

This MR documents a new `FRONT_COMMERCE_GEZY_IMAGE_PROXY_TIMEOUT_IN_MS` variable;

Fc 3008 Documented FRONT_COMMERCE_GEZY_IMAGE_PROXY_TIMEOUT_IN_MS

---

docs/100-upgrade/migration-guides/3.7-3.8.mdx

This add instruction to update PWA with cross-origin for basic auth protected manifests

chore(migration-guide): add infos about basic auth protected pwa

---

docs/03-extensions/theme-chocolatine/reference/features.mdx
docs/100-upgrade/migration-guides/3.8-3.9.mdx

This MR documents the changes induced by the refactor of `LayerFacets` in [!3796](https://gitlab.blackswift.cloud/front-commerce/front-commerce/-/merge_requests/3796).

chore: Document LayerFacets refactor

---

docs/02-guides/error-handling-for-routes.mdx
docs/02-guides/extension-features/_category_.yml
docs/02-guides/extension-features/components-map.mdx
docs/03-extensions/theme-chocolatine/reference/features.mdx
docs/04-api-reference/front-commerce-core/defineExtension.mdx
docs/04-api-reference/front-commerce-core/extension-features.mdx
docs/04-api-reference/front-commerce-core/react.mdx
docs/04-api-reference/front-commerce-remix/features.mdx
docs/100-upgrade/migration-guides/3.8-3.9.mdx

The changes introduce comprehensive documentation for new extension features in Front-Commerce, including the components map and error handling enhancements. Key additions include:
- A new guide on the "Components Map" that explains how to register and override component maps within extensions, providing examples and usage tips.
- Documentation for the `root-error-meta` feature, detailing how to generate meta tags for route error responses and providing example implementations.
- Introduction of the `registerFeature` hook in the API reference, explaining its parameters and usage for extending features in extensions.
- Updates to the error handling guide, emphasizing the use of the `root-error-meta` feature for customizing error page meta tags.
- Addition of the `useExtensionComponentMap` …

Documentation for Extension Features

---

docs/02-guides/magic-button/contribution-mode.mdx
docs/04-api-reference/front-commerce-core/config.mdx

This MR updates the documentation to be more specific about how the `FRONT_COMMERCE_CONTRIBUTION_MODE_FORCE` works.

docs: Updated contribution mode docs to specify how environment variable is processed

---

package.json
pnpm-lock.yaml
src/components/ChangelogFooter.tsx

This PR removes Hubsport forms from our documentation, as we don't use Hubspot anymore.

docs: Removed Hubspot form from docs as we don't use this anymore.

---

docs/100-upgrade/migration-guides/3.9-3.10.mdx

This documents the migration for product cross-sells in added popin.
TODO

Migration for Product Cross-Sells in `ProductAddedPopin`
