_config.yml
source/docs/advanced/server/add-http-endpoint.md
source/docs/essentials/add-a-page-client-side.md
source/docs/essentials/add-component-to-storybook.md
source/docs/essentials/create-a-business-component.md
source/docs/essentials/create-a-ui-component.md
source/docs/essentials/extend-the-graphql-schema.md
source/docs/essentials/extend-the-theme.md
source/docs/essentials/installation.md
source/docs/reference/configurations.md
source/docs/reference/front-commerce-js.md
source/help.md
source/index.md

See https://deploy-preview-41--elastic-austin-cf9d40.netlify.com/docs/reference/front-commerce-js.html for the `.front-commerce.js` page.
The only remaining dead links are the one related to the « vision » page.
We should settle on this…

Replace public todos and document `.front-commerce.js`

---

source/docs/reference/cli.md

This goes with the change made in the Skeleton's README: https://gitlab.com/front-commerce/front-commerce-skeleton/-/commit/2911b0b111dd59b1cb243444dfaf69b97358f30f

Document `test` script in front-commerce CLI

---

source/docs/advanced/checkout/overview.md
source/docs/advanced/graphql/overview.md
source/docs/advanced/payments/overview.md
source/docs/advanced/performance/overview.md
source/docs/advanced/production-ready/overview.md
source/docs/advanced/server/overview.md
source/docs/advanced/theme/overview.md
source/docs/magento1/installation.md
source/docs/magento1/overview.md
source/docs/magento2/overview.md
theme/layout/page.ejs

there was an issue where pages with the same title ("Overview") were
mixed up in the "algorithm", leading to incorrect next/prev pages
Thanks @astik for notifying us about this issue.
@JulienPradet: we'll have to pay attention to ids in the future, a convention could be to prefix them with their path. It seems to be better than using titles, because for consistency it could make sense to have several pages with the same one.
I'll merge right away but feel free to comment to keep the discussion going.

fix: use ids as unique identifier for determining prev/next pages

---

_config.yml
source/docs/appendices/migration-guides.md
source/docs/magento1/search-engine.md

* [Doc to install Elasticsearch or Algolia in Magento1](https://deploy-preview-161--heuristic-almeida-1a1f35.netlify.app/docs/magento1/search-engine.html)
* Improve a bit the 2.5 migration guide to help dealing with deprecated API
(related to questions we had this morning) : https://deploy-preview-161--heuristic-almeida-1a1f35.netlify.app/docs/appendices/migration-guides.html#Elasticsearch-in-a-dedicated-module

Search engine doc

---

_config.yml
source/docs/advanced/payments/affirm.md
source/docs/advanced/payments/overview.md
source/docs/advanced/payments/payline.md

This PR adds the current way to install Payline (early preview) in a Front-Commerce app.
I also fixed a minor mistake in Affirm's documentation.
[Preview :arrow_upper_right: ](https://deploy-preview-165--heuristic-almeida-1a1f35.netlify.app/docs/advanced/payments/payline.html)

Add an initial Payline documentation

---

source/docs/reference/cli.md

It was documented in https://developers.front-commerce.com/docs/advanced/theme/translations.html#Translate-what%E2%80%99s-in-your-components but is better also in the reference

Document the `--module` option for `front-commerce translate`

---

source/docs/advanced/graphql/dataloaders-and-cache-invalidation.md
source/docs/advanced/production-ready/checklist-before-production.md
source/docs/advanced/theme/form.md
source/docs/advanced/theme/server-side-rendering.md
source/docs/appendices/migration-guides.md
source/docs/essentials/adapt-theme-to-your-brand.md
source/docs/essentials/add-component-to-storybook.md
source/docs/essentials/create-a-business-component.md
source/docs/essentials/extend-the-theme.md
source/docs/magento2/headless-payments.md
source/docs/reference/cli.md

While checking some details in the documentation, I noticed a link still
referencing `master` while the branch has been renamed to `main`. So I fixed all
links still referencing `master` and while doing that I also found a broken link
to react-paginate history/changelog

Fix link pointing to master branch

---

source/docs/appendices/migration-guides.md
source/docs/appendices/release-notes.md

This PR rewords a sentence about the Node version bump (from user feedback) and adds the related "Release notes" section for 2.6.
BTW, Nginx supports Stale-While-Revalidate [since NGINX 1.11.10](https://www.nginx.com/blog/nginx-caching-guide/) so I've also updated the minimum Nginx documented version.
I used a ~2yo version that matches the Nginx plus LTS.

Clarify version of dependencies for 2.6

---

source/docs/appendices/migration-guides.md
source/docs/reference/configurations.md

This PR documents the change implemented in https://gitlab.com/front-commerce/front-commerce/-/merge_requests/506

`root_categories_path` is now unused in Front-Commerce

---

source/docs/reference/graphql-module-definition.md
source/docs/reference/remote-schema-helpers.md

* Simplify the `makeExecutor` example (and make it uses a function that exists in the example)
* Fix the argument of `uri` function used by `makeExecutor`

Simplify and fix makeExecutor documentation

---

source/docs/advanced/features/display-a-map.md

This PR updates the documentation for Maps to cope with a detected issue with the latest `react-leaflet` version released 20 days ago.

Document known issue with `react-leaflet`

---

source/docs/reference/environment-variables.md

This PR ensures that the documentation about `DEBUG` flag is up-to-date with the FC codebase.

Add missing debug flags from recent features

---

source/docs/prismic/routable-types.md

This is a followup of #208  to add an intro to the page.
We tried to start document pages with details about the context that may trigger the need for doing what is documented.\
It was an highlight from our research of good practices in documentation, as it allows readers to understand when this is (or not) relevant for them.

Add an intro to the Prismic Routable Types page

---

_config.yml
source/docs/prismic/expose-content.md
source/docs/prismic/index.md
source/docs/prismic/installation.md
source/docs/prismic/routable-types.md
source/docs/reference/environment-variables.md

Main page: https://deploy-preview-209--heuristic-almeida-1a1f35.netlify.app/docs/prismic/expose-content.html

Expose Prismic Content in the Graph

---

source/docs/advanced/theme/analytics.md

We've detected during support that the `enhancedEcommerce` option was not mentioned for Google Analytics, making it difficult to discover.
This PR might help with discoverability.

Include the `enhancedEcommerce` GA option in the default example

---

_config.yml
source/docs/prismic/content-slices.md
source/docs/prismic/index.md

This PR documents Prismic Slices support in FC.
Page Preview: https://deploy-preview-218--heuristic-almeida-1a1f35.netlify.app/docs/prismic/content-slices.html
I'll rebase/merge the updated `next` branch in it to ensure it is mergeable after merging #214

Document Content Slices support in the Prismic module

---

source/docs/appendices/migration-guides.md
source/docs/prismic/index.md
source/docs/prismic/installation.md

This PR updates the documentation according to Prismic features removed in https://gitlab.com/front-commerce/front-commerce-prismic/-/merge_requests/43
- installation instruction updated
- entry in the migration guide

Update documentation to stay in sync with removed Prismic features

---

source/docs/appendices/migration-guides.md
source/docs/prismic/installation.md
source/docs/reference/environment-variables.md

This PR documents the new data loader and debug namespace added in https://gitlab.com/front-commerce/front-commerce-prismic/-/merge_requests/44

Document Prismic API caching new feature

---

source/docs/advanced/payments/paypal.md

This PR documents a _hack_ needed to use the native Paypal module in Magento 1 that came again in support today.
It occurred several times already, and it is often difficult to find this SQL query.

Document Magento1 Paypal Standard SQL hack

---

source/docs/appendices/migration-guides.md
source/docs/prismic/installation.md

This PR updates the documentation to explain a bit how Prismic version gets refreshed.
Since https://gitlab.com/front-commerce/front-commerce-prismic/-/merge_requests/46 it should be more convenient.
The PR documents the `FRONT_COMMERCE_PRISMIC_API_CACHE_TTL_IN_SECONDS` environment variable so integrators can customize the behavior to their context.

Document automatic Prismic version update

---

source/docs/prismic/installation.md

that has now been replaced with the shop locale automatically
See https://gitlab.com/front-commerce/front-commerce-prismic/-/merge_requests/47 for the related MR.

Removed mentions to a legacy Prismic locale config

---

source/_posts/front-commerce-2.8.md
source/_posts/front-commerce-2.9.md
source/docs/appendices/migration-guides.md

This MR adds last minute migration guide additions and the 2.9.0 release post.
I'll merge it right away to publish the announcement, but reviews comments will still be acted upon afterwards.

Add a note about PaymentLoader not exported by default

---

source/docs/appendices/migration-guides.md

Related to : https://gitlab.com/front-commerce/front-commerce/-/merge_requests/762/
Addition of a new <WarnAlert> component requiring the new icon documented here.

Feat(alert): add a warning alert type

---

source/docs/essentials/create-a-business-component.md

We've got a feedback related to the `react-leaflet` version and usage instructions from the Essentials section was not up-to-date.
This MR update the instructions so that they can be copy-pasted.

Fix react-leaflet usage documented in Essentials

---

source/docs/appendices/migration-guides.md

This fixes the heading level for two titles in the migration guide

chore: add correct heading levels

---

source/docs/appendices/migration-guides.md

This PR documented the new styles added to modules for the ProductPicker component (Quick order).
---
I also removed recently added `<br>` that caused display issues (see https://developers.next.front-commerce.com/docs/appendices/migration-guides.html#Cookies-max-age-configuration)

Added `~theme/modules/ProductPicker/ProductPicker` new Sass partial to the migration guide

---

source/docs/appendices/migration-guides.md

https://deploy-preview-294--heuristic-almeida-1a1f35.netlify.app/docs/appendices/migration-guides.html

Document that front-commerce/magento2-module 2.5.0 is now required

---

source/docs/advanced/server/configurations.md

* some fixes (typos and leftover when I introduced `fetchRemoteConfiguration`)
* schema is a function
* add a note on where a configuraton provider is commonly registered
https://deploy-preview-298--heuristic-almeida-1a1f35.netlify.app/docs/advanced/server/configurations.html

Config provider page improvements

---

source/docs/essentials/add-component-to-storybook.md
source/docs/essentials/create-a-ui-component.md

Also added missing `Image` import in one of the example stories.
I picked `"calendar-full"` as a `"truck"` replacement for "48h shipping", as I have the feeling that was the most fitting icon among the currently exported icon list, but please do correct me if there's a better one.

chore(essentials): Fixed out-of-date icon names that weren't exported by FC anymore

---

source/docs/appendices/migration-guides.md

Following the removal of depreciated properties in the `Button` component, here's the migration documentation about it.

Added the removal of Button depreciations to the 2.14 migration guide

---

.github/workflows/ensure-consistency.yml
.prettierignore
package.json

To ensure code consistency.
This PR is aimed at making reviews easier. The CI is failing because content has not been reformatted.
Reformatting is done in #342 (CI is passing there)

CI: configure Github actions to add a linting step

---

_config.yml

fix: add RMA page to the menu for discoverability

---

theme/layout/page.ejs

so that readers are _a click away_ from providing us a feedback on documentation pages
Hypothesis: this CTA will increase the amount of typos notifications and help us iterate on the doc (content or organization)
It opens the Intercom Messenger with a fallback on our support email address.

feat(ux): add a direct feedback link on all pages

---

theme/layout/page.ejs

If you search in any instance other than production, the url's returned are absolute (with production origin), which results in unusable searching in either local development or preview deployments, this addresses that issue by removing the origin from the URL, only exposing the pathname, which results in navigatable links in current deployment/instance.
| Berfore | After    |
| ---------- | --------- |
|  <video src="https://user-images.githubusercontent.com/39598117/156334515-abd1aebf-747e-4550-8603-78b0040a39bb.mp4" />  |   <video src="https://user-images.githubusercontent.com/39598117/156334583-dd6ab3d4-b4cb-4a1d-a0c4-a46142ac8ab5.mp4" />  |

feat(dx): add relative paths for search result

---

theme/layout/page.ejs

When searching hashed content, only using the `pathname` does not suffice as we also need to include the `hash` to navigate to the correct sections.
Related to : https://github.com/front-commerce/developers.front-commerce.com/pull/346

fix(docs): adds the hash to the relative url

---

source/docs/appendices/troubleshooting.md

`front-commerce:config` isn't experimental anymore.
The `experimental` part of the debug flag has been removed, thus I removed it from the troubleshooting documentation has well.

chore(troubleshooting): Removed 'experimental' from front-commerce:config debug tag

---

source/docs/appendices/migration-guides.md

Add migration guide for Prismic advanced usage added in main branch (https://github.com/front-commerce/developers.front-commerce.com/pull/363)

chore(prismic): add migration guide for prismic module

---

source/docs/prismic/expose-content.md

Removes unclear braces in the arguments for the methods to query content.
```diff
- loadSingle(typeIdentifier[, options])
+ loadSingle(typeIdentifier, options)
- loadByUID(typeIdentifier, uid[, options])
+ loadByUID(typeIdentifier, uid, options)
- loadList(query[, options])
+ loadList(query, options) 
```

fix: fixes code syntax in prismic docs

---

source/docs/appendices/migration-guides.md
source/docs/reference/environment-variables.md

This PR documents the new feature flag added in https://gitlab.com/front-commerce/front-commerce/-/merge_requests/1152

Document deactivation of GraphQL Persisted Queries

---

source/index.md

From a feedback received, there are incorrect links to legacy demo instances on the home page.
This PR removes explicit links and redirects users to the new landing page designed specifically (and that will be kept up-to-date).
Preview: https://deploy-preview-375--heuristic-almeida-1a1f35.netlify.app/

Update demo links on the home page to redirect to the landing page

---

theme/source/style/_common-post.less
theme/source/style/_global/kbd.less

This adds styling to display kbd (keyboard) HTML elements in a more readable way.
| Before | <img width="462" alt="image" src="https://user-images.githubusercontent.com/39598117/161713209-c0f1b439-5c28-4342-8b48-570778ee4539.png"> |
|--------|-------------------------------------------------------------------------------------------------------------------------------------------|
| After  | <img width="481" alt="image" src="https://user-images.githubusercontent.com/39598117/161713096-28207eaf-2cb5-4e10-b3a1-53a7abcb4394.png"> |

Adds styling for kdb html element

---

source/docs/essentials/extend-the-graphql-schema.md

Following this example without the modules include you would run into an issue with the `.gql` import for the schema
Pre: prepare_modules
```bash
FRONT-COMMERCE  An error occured when running: webpack --silent --config /front-commerce-skeleton/node_modules/front-commerce/config/server/webpack.config.prod.js --entry server=/Projects/front-commerce-skeleton/node_modules/front-commerce/src/server/core/graphql/writeIntrospectionFiles.js -o /Projects/front-commerce-skeleton/build/server/core/graphql/writeIntrospectionFiles.js
```
Post: prepare_modules
```bash
WEBPACK  ./my-module/server/modules/click-counters/schema.gql 1:0
Module parse failed: Unexpected character '#' (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. …
```

fix: adds modules include in click counter example

---

source/_posts/front-commerce-2.9.md
source/_posts/prototype-ecommerce-applications-with-front-commerce-lite.md
source/docs/advanced/performance/cache-control-and-cdn.md
source/docs/advanced/shipping/add-new-shipping-data-in-graphql.md
source/docs/advanced/theme/analytics.md
source/docs/appendices/migration-guides.md
source/docs/appendices/release-notes.md
source/docs/reference/analytics-components.md

This fixes a bunch of broken links that were detected while crawling the docs, the only outstanding link is the `https://developers.front-commerce.com/docs/vision.html` which I could not find.

fix: fixes broken links detected in crawler

---

source/docs/reference/configurations.md

Improved the httpAuth documentation to avoid misunderstanding the way this configuration works as it is not obvious
https://deploy-preview-396--heuristic-almeida-1a1f35.netlify.app/docs/reference/configurations.html#config-httpAuth-js

fix(config): clarify the use of the httpAuth configuration

---

source/docs/appendices/migration-guides.md

As [per our discussion](https://gitlab.com/front-commerce/front-commerce/-/merge_requests/1231#note_927541557), this PR documents possible issues integrators could have in their project when upgrading to 2.15.
:arrow_right: https://deploy-preview-397--heuristic-almeida-1a1f35.netlify.app/docs/appendices/migration-guides.html#Environment-variables-quote-values-containing-or-characters

Document a minor breaking change in `dotenv` upgrade

---

source/docs/appendices/troubleshooting.md

This MR adds a section to the Troubleshooting area about https://gitlab.com/front-commerce/front-commerce/-/merge_requests/1264#note_944172133
Preview: https://deploy-preview-403--heuristic-almeida-1a1f35.netlify.app/docs/appendices/troubleshooting.html#I-have-an-error-Cannot-read-property-39-label-39-of-null-with-Magento-2-native-categories-listing

Document a known limitation with ElasticSuite for native M2 categories

---

source/docs/advanced/payments/hipay.md

The [location](https://gitlab.com/front-commerce/front-commerce/blob/dbb8658bd9b6dcd77253b83f91b0b48d4096e56e/src/web/theme/modules/User/Order/OrderMethod/PaymentMethodLabel.js) has changed

Update PaymentMethodLabel location

---

source/docs/advanced/features/invoices.md

function `userResDecorator` should return resBuffer for the proxy to work

Missing return of resBuffer

---

source/docs/advanced/payments/adyen.md

so that integrators don't install latest incompatible version
Indeed, [in 8.0.0 some APIs used by FC were changed in the module](https://github.com/Adyen/adyen-magento2/releases/tag/8.0.0) and we don't yet support them.
**Preview:** https://deploy-preview-410--heuristic-almeida-1a1f35.netlify.app/docs/advanced/payments/adyen.html#Install-and-configure-the-Adyen-Payment-Magento2-extension-7-2-lt-8-0

fix(adyen): clarify the M2 module supported version ranges

---

package-lock.json

As we have started using the latest npm for the core, it also makes sense to propagate that to the docs.

chore: update package.lock to version 2

---

source/docs/appendices/migration-guides.md
source/docs/appendices/release-notes.md
source/docs/appendices/release-process.md
source/docs/appendices/troubleshooting.md
source/docs/reference/analytics-components.md
source/docs/reference/cli.md
source/docs/reference/configurations.md
source/docs/reference/debugging.md
source/docs/reference/environment-variables.md
source/docs/reference/front-commerce-js.md
source/docs/reference/front-commerce-prepare.md
source/docs/reference/graphql-context.md
source/docs/reference/graphql-module-definition.md
source/docs/reference/remote-schema-helpers.md
source/docs/reference/routing.md
source/docs/reference/scripts.md
source/docs/reference/use-selected-product-with-configurable-options.md

Preview: https://deploy-preview-423--heuristic-almeida-1a1f35.netlify.app/docs/reference/front-commerce-js.html
This PR is a followup of #422, #408 and #416 with the last sections updated.
Sections included in this PR:
- Reference
- Appendices

SEO: reword introduction paragraph into descriptions - Part 4 (last)

---

docs/advanced/features/quickorder.mdx
docs/advanced/theme/analytics.mdx
docs/advanced/theme/layouts.mdx
docs/essentials/adapt-theme-to-your-brand.mdx
docs/essentials/add-component-to-storybook.mdx
docs/essentials/create-a-ui-component.mdx
package.json
src/components/Figure.tsx

from support
visible at: https://deploy-preview-457--heuristic-almeida-1a1f35.netlify.app/docs/advanced/theme/analytics#google-tag-manager (bottom of the page) vs. https://developers.front-commerce.com/docs/advanced/theme/analytics#google-tag-manager

fix: missing images on various pages

---

docs/appendices/migration-guides/index.mdx
docs/magento2/b2b.mdx

from our Adobe Commerce one
This is something that happened during the period of this release.
Previews: 
- https://deploy-preview-468--heuristic-almeida-1a1f35.netlify.app/docs/magento2/b2b#requirements
- https://deploy-preview-468--heuristic-almeida-1a1f35.netlify.app/docs/appendices/migration-guides/

docs(b2b): document the extraction of an Adobe B2B Magento module

---

docs/advanced/server/configurations.mdx
docs/appendices/troubleshooting.mdx

This aims to help integrator override express configuration by providing an easy copy-pastable example in their code.

docs(express): Documented way to override express configuration provider

---

docs/advanced/performance/assets-cdn-domain.mdx
docs/advanced/server/customize-response-http-headers.mdx

This MR documents how to customize CORS headers.
That has proven to be a useful thing to do for [some customers setting up a CDN](https://app.intercom.com/a/inbox/ehgzoeah/inbox/admin/5209667/conversation/188350900000078#part_id=comment-188350900000078-11599982732) or in other use cases.
For this reason, I also added a link to this new section from  the ["Serving assets from a CDN/custom domain" page (preview)](https://deploy-preview-477--heuristic-almeida-1a1f35.netlify.app/docs/advanced/performance/assets-cdn-domain).
**Preview:** https://deploy-preview-477--heuristic-almeida-1a1f35.netlify.app/docs/advanced/server/customize-response-http-headers#cross-origin-resource-sharing-aka-cors

Document how to customize CORS HTTP headers

---

docs/magento1/headless-payments.mdx

This MR adds a reminder to the Magento1 headless payments section roughly explaining how to create a custom method.
Based on [a feedback from support](https://app.intercom.com/a/inbox/ehgzoeah/inbox/admin/5209667/conversation/188350900000480#part_id=comment-188350900000480-16880376118), I added a reminder to ensure that the newly created payment method uses the correct workflow in the checkout process (client-side).

Minor improvement to Magento1's custom payment method guide

---

docs/advanced/graphql/dataloaders-and-cache-invalidation.mdx
docs/advanced/production-ready/sessions.mdx
docs/reference/configurations.mdx

Following support discussions, the need to clarify the config files for cloud appeared.
I took this opportunity to introduce the new FRONT_COMMERCE_CLOUD_REDIS_DB which will need to be implemented at some point.
- https://deploy-preview-484--heuristic-almeida-1a1f35.netlify.app/docs/reference/configurations#configcachingjs
- https://deploy-preview-484--heuristic-almeida-1a1f35.netlify.app/docs/advanced/graphql/dataloaders-and-cache-invalidation#redis
- https://deploy-preview-484--heuristic-almeida-1a1f35.netlify.app/docs/advanced/production-ready/sessions

fix(cloud): caching and session cloud variables

---

docs/appendices/migration-guides/archives.mdx

The addition of a line was not documented in the migration guide 
This answers to intercom : https://app.intercom.com/a/inbox/ehgzoeah/inbox/admin/5305956/conversation/188350900000497
See gitlab:  https://gitlab.com/search?search=%3C%25%3D%20htmlWebpackPlugin.tags.headTags%20%25%3E&nav_source=navbar&project_id=9218054&group_id=3903300&search_code=true&repository_ref=main

fix(migration): add index.html change on 2.7  to 2.8 migration

---

docs/magento2/detect-admin-users.mdx

We parse the data on the query from a encoded string, this previous example would cause the parsed data to result in  `"foo" : "bar"` instead of `{ foo: "bar" }` this would result in a syntaxt error
```
"foo":"bar"
SERVER  500 Unexpected server error
SyntaxError: Unexpected token : in JSON at position 5
```
I split them up in two commands (easier more readable running in browser, and second encoded to run in curl)
https://user-images.githubusercontent.com/39598117/194026292-fece7476-4a05-4228-ace0-bc88b0e6eee5.mp4

fix: encoding of adminData local testing

---

docs/bigcommerce/installation.mdx

This PR adds a new "Installation" page to the "BigCommerce" section.
I took the content from [a temporary internal MR](https://gitlab.com/front-commerce/front-commerce-skeleton/-/merge_requests/33) and formatted it for our doc.
:warning: I haven't set it up locally to verify it was still valid as I saw that it has been updated regularly since its creation.
:eyes: **Preview:** https://deploy-preview-498--heuristic-almeida-1a1f35.netlify.app/docs/bigcommerce/installation

Document BigCommerce module installation

---

docs/appendices/migration-guides/index.mdx

Removing the custom payment method feature announcement following the discussion https://github.com/front-commerce/developers.front-commerce.com/pull/487#discussion_r1001997562

fix(migration): remove custom payment method as a feature

---

docs/appendices/migration-guides/index.mdx
docs/magento2/advanced.mdx
docs/reference/environment-variables.mdx

This MR documents the new customer cache feature for Magento2
Preview:
- https://deploy-preview-517--heuristic-almeida-1a1f35.netlify.app/docs/magento2/advanced#caching-current-customers-information
- https://deploy-preview-517--heuristic-almeida-1a1f35.netlify.app/docs/appendices/migration-guides/#new-features-in-2190
- https://deploy-preview-517--heuristic-almeida-1a1f35.netlify.app/docs/reference/environment-variables#cache

Document current customer's information cache for Magento2

---

src/css/custom.css

While reading the release notes in dark mode I noticed that the primary colors really hard to read. I used the [docosaurus palette](https://docusaurus.io/docs/styling-layout#styling-your-site-with-infima) tool to find the closes accessible color to our original primary color.
| Before | After |
|--------|-------|
| ![image](https://user-images.githubusercontent.com/39598117/198337630-efd9b329-5ab3-4517-9727-a35c5e1ce2cb.png) | ![image](https://user-images.githubusercontent.com/39598117/198337670-7932578f-3ac5-4804-b8e2-d5e3063299cc.png) |

chore(accessibility): update darkmode primary color

---

docs/appendices/migration-guides/index.mdx
docs/reference/configurations.mdx

Following the change on how default address checkboxes are displayed, and the new `website.js` configuration.
[Migration guide](https://deploy-preview-540--heuristic-almeida-1a1f35.netlify.app/docs/appendices/migration-guides/#default-shipping-and-billing-address-support)
[website.js update](https://deploy-preview-540--heuristic-almeida-1a1f35.netlify.app/docs/reference/configurations#configwebsitejs)

Added documention on default address support changes

---

docs/advanced/analytics/plugins.mdx

As seen today during support, the snippet is incorrect. This MR fixes the syntax.
**Preview:** https://deploy-preview-543--heuristic-almeida-1a1f35.netlify.app/docs/advanced/analytics/plugins#google-tag-manager

fix: use correct syntax in copy/pastable GTM setup snippet

---

docs/bigcommerce/installation.mdx

`big-commerce-web` module was missing from the `front-commerce.js` diff.

Fix install step in BigCommerce doc

---

docs/magento2/search-engine.mdx
docs/reference/environment-variables.mdx

Documentation for Attraqt's recommendation module.
At the moment, the module only exposes a loader, so there is not much documentation to do about this beside what is done in this PR I think.
[Search Engine](https://deploy-preview-541--heuristic-almeida-1a1f35.netlify.app/docs/magento2/search-engine#attraqt-recommendations) - _Note: should it really be documented in the search engine article?_
[Environment variables](https://deploy-preview-541--heuristic-almeida-1a1f35.netlify.app/docs/reference/environment-variables#attraqt)

docs(attraqt):Added documentation for Attraqt's recommendation loader

---

docs/advanced/features/smart-forms.mdx

There was a file name in a snippet title that was unrelated to this file.
[URL](https://deploy-preview-554--heuristic-almeida-1a1f35.netlify.app/docs/advanced/features/smart-forms#usephonenumbervalidation)
Before:
After:

fix(docs): Removed wrong file title in snipet

---

docs/advanced/graphql/meta-modules.mdx
docs/advanced/graphql/remote-schemas.mdx
docs/advanced/payments/adyen.mdx
docs/advanced/payments/affirm.mdx
docs/advanced/payments/buybox.mdx
docs/advanced/payments/ingenico.mdx
docs/advanced/payments/payline.mdx
docs/advanced/payments/paypal.mdx
docs/advanced/payments/payzen.mdx
docs/advanced/payments/stripe.mdx
docs/appendices/migration-guides/archives.mdx
docs/essentials/add-component-to-storybook.mdx
docs/essentials/extend-the-graphql-schema.mdx
docs/magento1/search-engine.mdx
docs/magento2/graphql.mdx
docs/magento2/search-engine.mdx
docs/reference/front-commerce-js.mdx

Docs contained references of `FrontCommerceCore` module, which has been deprecated for a long time. this MR replaces every occurences of this module to the "new" `FrontCommerce`.

refactor(docs): Removed FrontCommerceCore references from docs

---

docs/advanced/features/invoices.mdx
docs/advanced/production-ready/media-middleware.mdx
docs/appendices/migration-guides/index.mdx

and add a section to the migration guide
This PR documents the change introduced [in this MR](https://gitlab.blackswift.cloud/front-commerce/front-commerce/-/merge_requests/1776)
:arrow_right: **[Preview](https://deploy-preview-569--heuristic-almeida-1a1f35.netlify.app/docs/appendices/migration-guides/#media-proxy-updated-to-send-a-custom-user-agent)**

Document the new import to use when using a custom media proxy

---

static/_headers

This PR allows our RSS feeds to be accessed by other websites client sides.
Example: https://developers.front-commerce.com/changelog/rss.xml

feat: add CORS headers to allow RSS inclusion everywhere

---

docs/advanced/analytics/legacy.mdx

Related a recent support request:
https://deploy-preview-573--heuristic-almeida-1a1f35.netlify.app/docs/advanced/analytics/legacy#google-analytics-4

fix: properly state GA4 non support in legacy analytics module

---

docs/advanced/features/external-logins/index.mdx
docs/advanced/features/in-stock-alert.mdx
docs/advanced/graphql/dataloaders-and-cache-invalidation.mdx
docs/advanced/payments/adyen.mdx
docs/advanced/payments/buybox.mdx
docs/advanced/payments/payline.mdx
docs/advanced/payments/paypal.mdx
docs/advanced/payments/payzen.mdx
docs/advanced/payments/stripe.mdx
docs/advanced/shipping/mondial-relay.mdx
docs/appendices/release-notes.mdx
docs/magento1/_category_.yml
docs/magento1/generate-api-doc.mdx
docs/magento1/headless-payments.mdx
docs/magento1/installation.mdx
docs/magento1/search-engine.mdx

This PR goes over the main parts of the documentation mentioning OpenMage or Magento 1 to ensure we mention both as much as possible… and with the correct "branded name" for OpenMage: **OpenMage LTS** (see [suggestion from Colin Mollenhour](https://github.com/OpenMage/OpenMage.github.io/pull/110#pullrequestreview-1234819332))

refactor: consolidate Magento 1 / OpenMage LTS branding across the doc

---

docs/appendices/release-process.mdx

This PR updates the release pace page by:
- rewording the introduction
- updating the 2022 releases with links to the changelog
- adding the 2023 calendar
It allows us to communicate date estimates to integrators or potential customers.
➡️ **[Preview](https://deploy-preview-568--heuristic-almeida-1a1f35.netlify.app/docs/appendices/release-process#when-to-expect-a-new-release)**

Update release calendar with 2023 dates

---

docs/essentials/extend-the-theme.mdx

This PR ensures that the example showing how to reuse an existing component from FC in an override works.
In 2.19.0, we've introduced [a new ESLint rule](https://gitlab.blackswift.cloud/front-commerce/front-commerce/-/merge_requests/1495) to warn in case the editor imports a component with FC core shortcut.\
Indeed, in this case we prefer developers to manually fix the import (to use `theme/xxx`) which is the most common case.
If developers really want to reuse FC component, they'll add an ESLint disable rule to express that they know what they're doing!
- [Preview](https://deploy-preview-593--heuristic-almeida-1a1f35.netlify.app/docs/essentials/extend-the-theme#reuse-the-original-component)

feat: add an ESLint disable instruction when reusing component

---

docs/magento2/search-engine.mdx

This MR adds the setup of Attraqt's Orchestrator Chrome extension, and also provides an example of utilisation of the loader  provided by Front-Commerce for this usecase.
As suggested in the comments on this PR, Front-Commerce could also provides with a module that basically does what the examples shows (+ `context`), and this should cover most of the usages of Attraqt Recommendation API.

feat(attraqt-recommendation): Added Attraqt Chrome extension setup and example

---

docs/advanced/payments/buybox.mdx

This PR adds a consistent title to [the BuyBox page](https://developers.front-commerce.com/docs/advanced/payments/buybox).
It seems it was never defined!
Before/After

fix(buybox): define a clean title to BuyBox page

---

changelog/front-commerce-2.6.mdx

https://developers.front-commerce.com/changelog/front-commerce-2.6/#new-feature-store-credits
vs.
https://deploy-preview-603--heuristic-almeida-1a1f35.netlify.app/changelog/front-commerce-2.6#new-feature-store-credits

fix: broken image in 2.6 post

---

docs/magento2/search-engine.mdx

https://deploy-preview-604--heuristic-almeida-1a1f35.netlify.app/docs/magento2/search-engine#algolia-not-connected-to-magento

Document how to setup algolia without the magento module

---

docs/magento2/search-engine.mdx

… and reindented the code block properly.
[Before](https://developers.front-commerce.com/docs/magento2/search-engine#using-attraqt-orchestrator-chrome-extension) / [After](https://deploy-preview-606--heuristic-almeida-1a1f35.netlify.app/docs/magento2/search-engine#using-attraqt-orchestrator-chrome-extension)

fix(attraqt): remove double return keyword

---

docs/appendices/migration-guides/index.mdx

Because it is needed to honor GraphQL queries now made by FC in 2.23.
- [**Preview**](https://deploy-preview-607--heuristic-almeida-1a1f35.netlify.app/docs/appendices/migration-guides/#2220---2230)

feat(migration): add M2 Commerce module minimal requirements to the migration guide

---

package.json
src/theme/BlogPostItem/Footer/index.tsx
src/theme/BlogPostItem/Footer/styles.module.css

This allows us to communicate with the readers on comments/questions they might have in the blog post.
It adds this comments section at the bottom which is driven through the GitHub Discissions api
https://deploy-preview-608--heuristic-almeida-1a1f35.netlify.app/blog/wsl-development-environment#conclusion

feat: add blog comments with giscus

---

versioned_docs/version-2.x/appendices/migration-guides/index.mdx
versioned_docs/version-2.x/magento2/using-magento-configuration.mdx

This PR documents the new `MagentoGraphQLConfig` introduced in [this MR](https://gitlab.blackswift.cloud/front-commerce/front-commerce/-/merge_requests/1845).
**Preview:** [page](https://deploy-preview-625--heuristic-almeida-1a1f35.netlify.app/docs/2.x/magento2/using-magento-configuration#use-magentos-storeconfig-graphql-query) and [migration guide](https://deploy-preview-625--heuristic-almeida-1a1f35.netlify.app/docs/2.x/appendices/migration-guides/#new-features-in-2230)

Document `MagentoGraphQLConfig` loader to access Magento configurations

---

versioned_docs/version-2.x/magento2/b2b.mdx

This PR updates known issues for the Negotiable quotes in Magento2, based on evolutions [that landed in this MR](https://gitlab.blackswift.cloud/front-commerce/front-commerce/-/merge_requests/1920).
- company permissions are now supported
- … except the company-level feature toggle
[**Preview**](https://deploy-preview-628--heuristic-almeida-1a1f35.netlify.app/docs/2.x/magento2/b2b#front-commerce-does-not-take-into-account-per-company-feature-deactivation)

Negotiable quotes: update known issues with company permissions

---

package.json

This PR fixes Netlify builds by providing a `pnpm` version explicitely, as per https://docs.netlify.com/configure-builds/manage-dependencies/#pnpm
Builds had the following error:
> Found pnpm version (7.13.4) that doesn't match expected ()
> Usage Error: Invalid package manager specification in CLI arguments; expected a semver version, range, or tag
It ignored the pnpm lockfile and led to peerdependencies errors, breaking the build.

fix(build): add explicit pnpm version range

---

versioned_docs/version-2.x/advanced/theme/route-dispatcher.mdx

Goes hand in hand with https://gitlab.blackswift.cloud/front-commerce/front-commerce/-/merge_requests/1932

fix: do not document deprecated URL property on custom url matcher

---

versioned_docs/version-2.x/magento1/installation.mdx

To keep what is removed in https://gitlab.blackswift.cloud/front-commerce/magento1-module-front-commerce/-/merge_requests/80 plus some improvements
Preview: https://deploy-preview-636--heuristic-almeida-1a1f35.netlify.app/docs/2.x/magento1/installation

Improve Magento1 installation documentation

---

versioned_docs/version-2.x/advanced/_category_.yml
versioned_docs/version-2.x/bigcommerce/_category_.yml
versioned_docs/version-2.x/concepts/_category_.yml
versioned_docs/version-2.x/essentials/_category_.yml
versioned_docs/version-2.x/magento1/_category_.yml
versioned_docs/version-2.x/magento2/_category_.yml
versioned_docs/version-2.x/prismic/_category_.yml
versioned_docs/version-2.x/reference/_category_.yml
versioned_docs/version-2.x/reference/environment-variables.mdx
versioned_docs/version-2.x/wordpress/_category_.yml
versioned_docs/version-2.x/wordpress/installation.mdx

See also https://gitlab.blackswift.cloud/front-commerce/front-commerce-wordpress/-/merge_requests/20
Preview:
* https://deploy-preview-639--heuristic-almeida-1a1f35.netlify.app/docs/2.x/wordpress/installation
* https://deploy-preview-639--heuristic-almeida-1a1f35.netlify.app/docs/2.x/reference/environment-variables#wordpress

Initialize front-commerce-wordpress module documentation

---

versioned_docs/version-2.x/appendices/migration-guides/index.mdx

This MR fixes changes on the migration guide that are outdated, notably commit links that were superseded.
https://deploy-preview-646--heuristic-almeida-1a1f35.netlify.app/docs/2.x/appendices/migration-guides/#adobe-commerce-negotiable-quotes

fix(negotiable-quote): fix commit links in migration guide

---

versioned_docs/version-2.x/prismic/preview.mdx

This was required for one of the first implementations of the PrismicPreview, but the latest one works with cookies to get the repository name, so this is no longer required

Update Prismic preview.mdx

---

versioned_docs/version-2.x/reference/_category_.yml

fix: make sure Wordpress is before Reference

---

docs/api-reference/_category_.yml
docs/api-reference/front-commerce-remix.mdx
docs/migration/_category_.yml
src/css/custom.css

This adds the documentation and API reference for the `@front-commerce/remix` package.
https://deploy-preview-654--heuristic-almeida-1a1f35.netlify.app/docs/remixed/api-reference/front-commerce-remix

chore(remix): add FrontCommerceApp documentation

---

versioned_docs/version-2.x/advanced/payments/stripe.mdx
versioned_docs/version-2.x/appendices/migration-guides/index.mdx

https://deploy-preview-662--heuristic-almeida-1a1f35.netlify.app/docs/2.x/advanced/payments/stripe#optional-enable-apple-pay-andor-google-pay
https://deploy-preview-662--heuristic-almeida-1a1f35.netlify.app/docs/2.x/appendices/migration-guides/#apple-pay-and-google-pay-support-with-stripe

Google Pay and Apple Pay support with Stripe

---

versioned_docs/version-2.x/advanced/images-adapters/akamai-image-manager.mdx

This PR updates the upcoming documentation to ensure the module renaming tackled in https://gitlab.blackswift.cloud/front-commerce/front-commerce/-/merge_requests/2051 is reflected in the documentation.

Akamai Image Manager: rename module

---

versioned_docs/version-2.x/advanced/images-adapters/custom-adapter.mdx
versioned_docs/version-2.x/appendices/migration-guides/index.mdx

see https://gitlab.blackswift.cloud/front-commerce/front-commerce/-/merge_requests/2037
- [Migration Guide](https://deploy-preview-661--heuristic-almeida-1a1f35.netlify.app/docs/2.x/appendices/migration-guides/#imageadapters-without-multiple-sources)
- [Custom ImageAdapter](https://deploy-preview-661--heuristic-almeida-1a1f35.netlify.app/docs/2.x/advanced/images-adapters/custom-adapter#changing-the-generated-sources-for-srcset)

feat(image-adapters): allow custom image sources (FC-1256)

---

versioned_docs/version-2.x/advanced/images-adapters/akamai-image-manager.mdx
versioned_docs/version-2.x/appendices/migration-guides/index.mdx

This PR ensures that the Akamai Image Manager documented feature is up-to-date with the latest version and consistent with other.
It:
- adds a note about it in the migration guide's new features
- adds the description in the page
- documents the `akamai.paths` configuration
- rewords the FC Cloud related block with a CTA to contact us
Preview:
- [Akamai image manager](https://deploy-preview-666--heuristic-almeida-1a1f35.netlify.app/docs/2.x/advanced/images-adapters/akamai-image-manager)
- [Migration guide](https://deploy-preview-666--heuristic-almeida-1a1f35.netlify.app/docs/2.x/appendices/migration-guides/#new-features-in-2240)

Akamai Image Manager: add additional configuration + mention in migration guide

---

package.json
pnpm-lock.yaml

Fixes the following error logs when running in development
```
[ERROR] TSError: ⨯ Unable to compile TypeScript:
docusaurus.config.js:19:19 - error TS2307: Cannot find module '@docusaurus/types' or its corresponding type declarations.
19 /** @type {import('@docusaurus/types').Config} */
~~~~~~~~~~~~~~~~~~~
at createTSError (/home/paul/Projects/developers.front-commerce.com/node_modules/.pnpm/ts-node@10.9.1_@types+node@18.15.11_typescript@4.9.4/node_modules/ts-node/src/index.ts:859:12)
at reportTSError (/home/paul/Projects/developers.front-commerce.com/node_modules/.pnpm/ts-node@10.9.1_@types+node@18.15.11_typescript@4.9.4/node_modules/ts-node/src/index.ts:863:19)
at getOutput (/home/paul/Projects/developers.front-commerce.com/node_modules/.pnpm/ts-node@10.9.1_@types+node@18.15.11_typescript …
```

Fixes docosaurus types

---

versioned_docs/version-2.x/advanced/payments/adyen.mdx
versioned_docs/version-2.x/appendices/migration-guides/index.mdx

This MR updates the M2 Adyen installation procedure to explain more clearly how to configure URLs for headless use cases.
It also adds a word about this for existing projects migrating to 2.18 (and upgrading their Adyen module).
Preview:
- [Adyen install section](https://deploy-preview-683--heuristic-almeida-1a1f35.netlify.app/docs/2.x/advanced/payments/adyen#install-and-configure-the-adyen_payment-magento2-extension-72--90)
- [Migration guide](https://deploy-preview-683--heuristic-almeida-1a1f35.netlify.app/docs/2.x/appendices/migration-guides/#magento2-adyen-module-update)

fix(adyen): add more detailed explanations about configuring M2 extension

---

versioned_docs/version-2.x/advanced/analytics/getting-started.mdx
versioned_docs/version-2.x/advanced/analytics/plugins.mdx

This MR document an issue about sending cookie services to the datalayer.
[Analytics page](https://deploy-preview-681--heuristic-almeida-1a1f35.netlify.app/docs/2.x/advanced/analytics/getting-started#retrieve-authorized-cookie-services-in-analytics)\
[GTM mention](https://deploy-preview-681--heuristic-almeida-1a1f35.netlify.app/docs/2.x/advanced/analytics/plugins#retrieve-authorized-cookie-services-in-gtms-datalayer)

chore: Document workaround for sending cookies services to datalayer

---

versioned_docs/version-2.x/appendices/migration-guides/index.mdx

The migration guide related to the Magic Button is incomplete. This patch adds some missing instructions.

Complete migration guide related to Magic Button implementation

---

versioned_docs/version-2.x/advanced/analytics/plugins.mdx

Our current documentation features a setting (`userConsents`) we implemented in our legacy analytics module but that isn't available in `@analytics/google-tag-manager`.
This MR fixes this example with another example that provides the same effect.
[GTM documentation](https://deploy-preview-684--heuristic-almeida-1a1f35.netlify.app/docs/2.x/advanced/analytics/plugins#google-tag-manager)

Fixed GTM plugin example settings

---

versioned_docs/version-2.x/advanced/payments/stripe.mdx
versioned_docs/version-2.x/appendices/migration-guides/index.mdx
versioned_docs/version-2.x/magento2/b2b.mdx

This PR documents Stripe's support for Negotiable Quote implemented in the 2.25 version.
Impacted pages (preview):
- [Migration guide section](https://deploy-preview-688--heuristic-almeida-1a1f35.netlify.app/docs/2.x/appendices/migration-guides/#negotiable-quotes-online-payments)
- [Negotiable quotes "Known issues" section update](https://deploy-preview-688--heuristic-almeida-1a1f35.netlify.app/docs/2.x/magento2/b2b#advanced-shipping-methods-and-online-payments-arent-fully-supported) (I also moved this part first, since it's a quite important limitation to be aware of)
- [Stripe installation update for Adobe B2B use](https://deploy-preview-688--heuristic-almeida-1a1f35.netlify.app/docs/2.x/advanced/payments/stripe#adobe-commerce-b2b)

Document Stripe for Negotiable Quote

---

versioned_docs/version-2.x/appendices/migration-guides/index.mdx
versioned_docs/version-2.x/reference/configurations.mdx

- [Migration Guide](https://deploy-preview-690--heuristic-almeida-1a1f35.netlify.app/docs/2.x/appendices/migration-guides/#use-facet-labels-as-values)
- [Documentation](https://deploy-preview-690--heuristic-almeida-1a1f35.netlify.app/docs/2.x/reference/configurations#configwebsitejs)

docs: use attribute labels as values

---

versioned_docs/version-2.x/appendices/migration-guides/index.mdx

This fixes the prettier linting of the migration guide, https://github.com/front-commerce/developers.front-commerce.com/pull/690 was merged while experiencing [this issue](https://github.com/prettier/prettier-vscode/issues/3020), causing other MR's to have unnecessary changes.

fix: prettier linting of migration guide

---

versioned_docs/version-2.x/appendices/migration-guides/index.mdx

This MR documents the new default sorting behavior for ElasticSearch datasource in the migration guide.
[Migration guide link](https://deploy-preview-693--heuristic-almeida-1a1f35.netlify.app/docs/2.x/appendices/migration-guides/#new-default-sorting-method-for-elasticsearch-datasource)

ElasticSearch: Default sorting documentation

---

versioned_docs/version-2.x/magento1/search-engine.mdx
versioned_docs/version-2.x/magento2/search-engine.mdx

This PR adds documentation for the `refinementFacetsOnly` feature flag that alters the way facets are retrieved for ElasticSearch datasource.

Elasticsearch multiple facet values

---

versioned_docs/version-2.x/appendices/migration-guides/index.mdx

Feedback from support where this resolver was redefined than displaying an order was broken

Migration guide: add the case where the resolver for `Shipment.trackingDetails` is redefined

---

versioned_docs/version-2.x/magic-button/auto-refresh.mdx
versioned_docs/version-2.x/magic-button/preview-mode.mdx

To follow the same ordering which we use in the Editorial Toolbox

fix: sort order for magic-button features

---

src/components/SinceVersion.tsx
versioned_docs/version-2.x/advanced/graphql/dataloaders-and-cache-invalidation.mdx
versioned_docs/version-2.x/appendices/migration-guides/index.mdx

This MR updates the `PerMagentoCustomerTaxZone` cache strategy documentation to mention the newly introduced support for Magento1 backends.
It also updates the `<SinceVersion />` component, so we could document progressive releases of features per platform.
**[Preview](https://deploy-preview-709--heuristic-almeida-1a1f35.netlify.app/docs/2.x/advanced/graphql/dataloaders-and-cache-invalidation#permagentocustomertaxzone)** + mention in [Migration guide](https://deploy-preview-709--heuristic-almeida-1a1f35.netlify.app/docs/2.x/appendices/migration-guides/#2250---2260)

Document `PerMagentoCustomerTaxZone` support for Magento1

---

versioned_docs/version-2.x/advanced/checkout/temporary-shipping-address.mdx

This PR add documentation on how to set up temporary shipping address in checkout
[Added Page](https://deploy-preview-702--heuristic-almeida-1a1f35.netlify.app/docs/2.x/advanced/checkout/temporary-shipping-address)

feat(temporary-shipping-address): add instruction on how to do it

---

docusaurus.config.js
versioned_docs/version-2.x/advanced/features/display-a-map.mdx
versioned_docs/version-2.x/advanced/features/external-logins/advanced-external-logins.mdx
versioned_docs/version-2.x/advanced/features/external-logins/index.mdx
versioned_docs/version-2.x/advanced/shipping/chronorelais.mdx
versioned_docs/version-2.x/advanced/shipping/colissimo.mdx
versioned_docs/version-2.x/advanced/shipping/mondial-relay.mdx
versioned_docs/version-2.x/appendices/migration-guides/archives.mdx
versioned_docs/version-2.x/appendices/migration-guides/index.mdx
versioned_docs/version-2.x/essentials/add-a-page-client-side.mdx
versioned_docs/version-2.x/essentials/add-component-to-storybook.mdx
versioned_docs/version-2.x/essentials/create-a-business-component.mdx
versioned_docs/version-2.x/essentials/installation.mdx
versioned_docs/version-2.x/magento1/advanced.mdx
versioned_docs/version-2.x/magento2/add-new-attribute.mdx
versioned_docs/version-2.x/magento2/advanced.mdx
versioned_docs/version-2.x/wordpress/installation.mdx

I just found that there was a missing `-` on all pages titles, and ran a quick search/replace in the whole documentation to ensure FC is written with a `-` everywhere.

chore: add `-` to all Front-Commerce mentions in the doc

---

versioned_docs/version-2.x/advanced/graphql/dataloaders-and-cache-invalidation.mdx
versioned_docs/version-2.x/appendices/migration-guides/index.mdx

This MR documents the configuration + default value change introduced in https://gitlab.blackswift.cloud/front-commerce/front-commerce/-/merge_requests/2243
**[Preview](https://deploy-preview-720--heuristic-almeida-1a1f35.netlify.app/docs/2.x/appendices/migration-guides/#redis-invalidation-scan-iterations-size-configuration-invalidationscaniterationsize)**

Redis: configurable scan iteration size updates in 2.26

---

versioned_docs/version-2.x/appendices/migration-guides/index.mdx

This PR brings a minor improvement to the Migration guide: it adds a reminder with the command integrators could use to update FC in their project.
It is a command that we're regularly asked about, and it felt to be a good idea to have it here.
**[Preview](https://deploy-preview-713--heuristic-almeida-1a1f35.netlify.app/docs/2.x/appendices/migration-guides/)**

Document the `npm install` command to upgrade FC in a project

---

versioned_docs/version-2.x/appendices/migration-guides/index.mdx

This PR adds an admonition to the 2.25 migration guide section about using labels as values.
When upgrading, an integrator required support because they haven't thought about updating their resolvers ([conversation](https://app.intercom.com/a/inbox/ehgzoeah/inbox/shared/all/conversation/188350900000936?view=List)). Having custom logic for layers isn't such uncommon, and it makes sense to add a note a bit more explicit so integrators could autonomously update their codebase.
**[Preview](https://deploy-preview-721--heuristic-almeida-1a1f35.netlify.app/docs/2.x/appendices/migration-guides/#use-facet-labels-as-values)**

Migration guide: Add an explicit note about resolvers override for label as values

---

versioned_docs/version-2.x/magento1/search-engine.mdx

Following [this intercom ticket](https://app.intercom.com/a/inbox/ehgzoeah/inbox/shared/mentions/conversation/188350900000904?view=List), we noticed the documentation could be confusing as to what feature exactly was usable natively with magento1 and  magento2.

fix: Changed wording on netive search for magento1 and magento2

---

docusaurus.config.js
src/pages/community.md

This PR adds a new "Community" page in the header navigation menu.
This page allows to centralize all known community projects, in order to:
- increase discoverability of "non-core" features
- highlight teams and individuals who contribute to our community
**[Preview](https://deploy-preview-715--heuristic-almeida-1a1f35.netlify.app/community)**

Add a new "Community" page, to centralize community initiatives.

---

versioned_docs/version-2.x/appendices/migration-guides/index.mdx

[Related intercom issue](https://app.intercom.com/a/inbox/ehgzoeah/inbox/admin/5398798/conversation/188350900000942?view=List).
This MR adds a note regarding FCC customers to ask support to change Node version when upgrading to 2.25+.
[Related changes block](https://deploy-preview-725--heuristic-almeida-1a1f35.netlify.app/docs/2.x/appendices/migration-guides/#drop-support-of-node-14)

Added a note about upgrading CI Node version on FCC

---

docs/migration/manual-migration.mdx

Because we have more variables with Axios timeouts and Magic Button features. See [discussion](https://gitlab.blackswift.cloud/front-commerce/front-commerce/-/merge_requests/2248/diffs#note_93164) for context.
**[Preview](https://deploy-preview-726--heuristic-almeida-1a1f35.netlify.app/docs/remixed/migration/manual-migration#magento)**

Remix: document more renamed Magento-related env vars

---

docs/api-reference/front-commerce-remix/generate-metas.mdx
docs/migration/manual-migration.mdx

This PR introduce migration for the HomeSeo component removal and explain the `generateMetas` helper

feat(metadata): adding HomeSeo and generateMetas migration

---

docs/migration/manual-migration.mdx

This adds the manual migration guide for scss mixin and media queries

docs(scss): add migration guide for scss mixin and media queries

---

docs/migration/compat-mode.mdx

This PR documents the `@front-commerce/compat` module, along with the feature flag introduced in https://gitlab.blackswift.cloud/front-commerce/front-commerce/-/merge_requests/2328
- [**Preview**](https://deploy-preview-732--heuristic-almeida-1a1f35.netlify.app/docs/remixed/migration/compat-mode)

FC Remixed: document compat mode and new `v2_compat.useApolloClientQueries` feature flag

---

docs/migration/deprecated-code-removal.mdx

This PR updates the link to the MR that handles WysiwygV2 renaming.
- [Preview](https://deploy-preview-733--heuristic-almeida-1a1f35.netlify.app/docs/remixed/migration/deprecated-code-removal#wysiwygv1)

Update WysiwygV2 related documentation link

---

docusaurus.config.js

This fixes the banner which is displayed at the top of the docs for the `remixed` version
| Before | After  |
| ------- | ------ |
| ![image](https://github.com/front-commerce/developers.front-commerce.com/assets/39598117/e8ecb791-1e68-42e0-8080-ae8a71404fd2) | ![image](https://github.com/front-commerce/developers.front-commerce.com/assets/39598117/53a98f56-c679-4694-aa4c-f031962b2332) |

fix: version banner for future remixed docs

---

docs/api-reference/front-commerce-core/_category_.yml
docs/api-reference/front-commerce-core/create-resized-image-response.mdx
docs/api-reference/front-commerce-core/index.mdx
docs/migration/manual-migration.mdx

https://gitlab.blackswift.cloud/front-commerce/front-commerce/-/merge_requests/2377
- https://deploy-preview-738--heuristic-almeida-1a1f35.netlify.app/docs/remixed/api-reference/front-commerce-core/create-resized-image-response
- https://deploy-preview-738--heuristic-almeida-1a1f35.netlify.app/docs/remixed/migration/manual-migration#makeimageproxyrouter--createresizedimageresponse

chore: add documentation for the createResizedImageResponse

---

versioned_docs/version-2.x/advanced/payments/adyen.mdx

related to a recent support request.
It should have been documented after merging [this MR](https://gitlab.blackswift.cloud/front-commerce/front-commerce/-/merge_requests/1775).

fix: Apple Pay only show up on Apple devices

---

versioned_docs/version-2.x/appendices/release-notes.mdx
versioned_docs/version-2.x/magento2/installation.mdx

This MR updates the minimum supported version of Magento2 and the minimum FC Module version
[Added warn about minimum module version](https://deploy-preview-743--heuristic-almeida-1a1f35.netlify.app/docs/2.x/magento2/installation#module-compatibility)
[Updated compatible version](https://deploy-preview-743--heuristic-almeida-1a1f35.netlify.app/docs/2.x/appendices/release-notes#latest-version)

feat(magento2): update supported magento version

---

versioned_docs/version-2.x/magento2/log-as-customer.mdx

A simple work around is to disable the protection in the admin interface (which is probably okish in most cases).
While at it, I also tried to improve the paragraph about ACL
Preview: https://deploy-preview-746--heuristic-almeida-1a1f35.netlify.app/docs/2.x/magento2/log-as-customer

Note about Firefox Enhanced Tracking Protection preventing log in as customer from working properly

---

docs/migration/manual-migration.mdx

This MR document the deprecation (removal) of `withCartTracking` HOC, replaced by `useCartTracking` hook.
[Related MR](https://gitlab.blackswift.cloud/front-commerce/front-commerce/-/merge_requests/2416)
[Preview](https://deploy-preview-745--heuristic-almeida-1a1f35.netlify.app/docs/remixed/migration/manual-migration#withcarttracking-replaced-with-usecarttracking)

Document withCartTracking deprecation

---

docs/migration/compat-mode.mdx

This PR documents the feature flag introduced in https://gitlab.blackswift.cloud/front-commerce/front-commerce/-/merge_requests/2417
**[Preview](https://deploy-preview-744--heuristic-almeida-1a1f35.netlify.app/docs/remixed/migration/compat-mode#useapolloclientssr)**

Document the `v2_compat.useApolloClientSSR` feature flag

---

docs/migration/manual-migration.mdx

This PR documents the removal of `withLogoutMutation` HOC, in favor of an `action` in a Remix route file.
Related MR: [!2420](https://gitlab.blackswift.cloud/front-commerce/front-commerce/-/merge_requests/2420)

Documentated withLogoutMutation HOC removal

---

versioned_docs/version-2.x/advanced/payments/stripe.mdx
versioned_docs/version-2.x/reference/environment-variables.mdx

Documentation for FRONT_COMMERCE_STRIPE_MAX_NETWORK_RETRY introduced in https://gitlab.blackswift.cloud/front-commerce/front-commerce/-/merge_requests/2468 (also added stripe env variables to https://developers.front-commerce.com/docs/2.x/reference/environment-variables).
https://deploy-preview-754--heuristic-almeida-1a1f35.netlify.app/docs/2.x/advanced/payments/stripe#advanced-network-retries

Document FRONT_COMMERCE_STRIPE_MAX_NETWORK_RETRY

---

versioned_docs/version-2.x/magento1/exposing-additional-attributes.mdx

Make clear that `custom_attribute` is an example by renaming it and writing it.

Improve exposing additional attribute page example

---

src/css/custom.css

This fixes the alignment on html `code` tags.
https://github.com/front-commerce/developers.front-commerce.com/assets/39598117/76524ce0-8e1c-43d2-8fa0-fd2b1a59043a

chore: fix `code` tag alignment

---

versioned_docs/version-2.x/magic-button/x-ray.mdx

… we documented `@storeContentDirective` instead of `@storefrontContent` :shrug: 
Also, the code example was incorrect.
**[Preview](https://deploy-preview-761--heuristic-almeida-1a1f35.netlify.app/docs/2.x/magic-button/x-ray#x-ray-on-custom-types)**

Fix the X-Ray documentation to use the correct `@storefrontContent` directive name

---

versioned_docs/version-2.x/advanced/production-ready/logging.mdx

Try on version 2.20, but the path for import loggingService is invalid, we need to use `server/core/logs/loggingService`

Bad loggingService import path

---

docs/migration/manual-migration.mdx

This PR documents changes made to `EmptyCart` and `EnhanceEmptyCart` as they contain a breaking change for integrators.
[Related MR](https://gitlab.blackswift.cloud/front-commerce/front-commerce/-/merge_requests/2525)
[Preview](https://deploy-preview-760--heuristic-almeida-1a1f35.netlify.app/docs/remixed/migration/manual-migration#emptycart-refactor)

Refactor empty cart enhancer

---

docs/migration/manual-migration.mdx

This MR documents a list of enhancers that were removed alongside usages of `react-apollo` in theme-chocolatine.
[Preview](https://deploy-preview-765--heuristic-almeida-1a1f35.netlify.app/docs/remixed/migration/manual-migration#removed-menunavigation-component)

Document removed enhancers following client-side graphql usage removal

---

docs/migration/manual-migration.mdx

This MR documents the removal done in https://gitlab.blackswift.cloud/front-commerce/front-commerce/-/commit/8ddc943ba38d7a71a4e8830c60de4330bf1818a1
**[Preview](https://deploy-preview-766--heuristic-almeida-1a1f35.netlify.app/docs/remixed/migration/manual-migration#usedevice-removal)**

Document `useDevice()` removal

---

docs/04-api-reference/front-commerce-core/create-resized-image-response.mdx
docs/04-api-reference/front-commerce-remix/front-commerce-app.mdx
docs/04-api-reference/front-commerce-remix/generate-metas.mdx
docs/04-api-reference/front-commerce-remix/index.mdx
docs/migration/manual-migration.mdx

This updates our documentation to reference remix v2
- https://gitlab.blackswift.cloud/front-commerce/front-commerce/-/merge_requests/2559
- https://remix.run/docs/en/2.0.1/start/v2

chore: update docs to reference remix v2

---

docs/03-extensions/theme-chocolatine/reference/css-variables.mdx

Regression introduced in #775.
The build currently is broken on `main`:  https://app.netlify.com/sites/heuristic-almeida-1a1f35/deploys/651d55e1586ef40008be0d2e
This patch links to "Customize the styles" page instead. I guess that was the initial intent.

fix: broken link on CSS variables reference

---

docs/04-api-reference/front-commerce-core/defineExtension.mdx

This adds documentation for extension in `@front-commerce/core`
https://deploy-preview-780--heuristic-almeida-1a1f35.netlify.app/docs/remixed/api-reference/front-commerce-core/extensions

doc: adding documentation for extension definition

---

docs/04-api-reference/front-commerce-core/config.mdx

This MR adds doc for `@front-commerce/core/config`
https://deploy-preview-782--heuristic-almeida-1a1f35.netlify.app/docs/remixed/api-reference/front-commerce-core/config

doc: core/config documentation

---

docs/04-api-reference/front-commerce-core/defineExtension.mdx
docs/04-api-reference/front-commerce-remix/defineRemixExtension.mdx

This documents the API for the `defineRemixExtension` introduced in https://gitlab.blackswift.cloud/front-commerce/front-commerce/-/merge_requests/2716
- Document an example for layout implementation `_main.tsx` (done in https://github.com/front-commerce/developers.front-commerce.com/pull/797)
- Document an example for loading data (see FC-1750)
- https://deploy-preview-796--heuristic-almeida-1a1f35.netlify.app/docs/remixed/api-reference/front-commerce-remix/defineRemixExtension

chore: document `defineRemixExtension`

---

docs/02-guides/extend-route-layout.mdx

This documents how to extend existing `layout` routes used in Front-Commmerce theme-chocolatine.
- https://deploy-preview-797--heuristic-almeida-1a1f35.netlify.app/docs/remixed/guides/extend-route-layout

chore: document extending layout routes

---

versioned_docs/version-2.x/magento1/installation.mdx

This MR documents how to configure reviews for Magento1.
Related changes MR: https://gitlab.blackswift.cloud/front-commerce/front-commerce/-/merge_requests/2758
Preview: https://deploy-preview-803--heuristic-almeida-1a1f35.netlify.app/docs/2.x/magento1/installation#reviews-configuration

Product reviews for Magento 1

---

versioned_docs/version-2.x/appendices/migration-guides/index.mdx
versioned_docs/version-2.x/magento1/installation.mdx

Following https://github.com/front-commerce/developers.front-commerce.com/pull/803, this MR adds the required Magento1 module version to the feature's documentation.

Added required Magento 1 module version for Review feature.

---

docs/02-guides/translate-your-application.mdx
docs/04-api-reference/front-commerce-core/defineExtension.mdx
docs/04-api-reference/front-commerce-remix/index.mdx
docs/migration/features-removal.mdx

This closes FC-1396 and FC-1811
Added documentation for the CLI of `@front-commerce/remix` package
- https://deploy-preview-809--heuristic-almeida-1a1f35.netlify.app/docs/remixed/migration/features-removal#i18n-iso-countries-removal
- https://deploy-preview-809--heuristic-almeida-1a1f35.netlify.app/docs/remixed/api-reference/front-commerce-remix/#cli
- https://deploy-preview-809--heuristic-almeida-1a1f35.netlify.app/docs/remixed/guides/translate-your-application

Document Translations

---

versioned_docs/version-2.x/magento1/search-engine.mdx

This MR documents Attraqt datasource and recommendations support for Magento1.
[Related MR](https://gitlab.blackswift.cloud/front-commerce/front-commerce/-/merge_requests/2816)
[Preview](https://deploy-preview-810--heuristic-almeida-1a1f35.netlify.app/docs/2.x/magento1/search-engine#attraqt)
_Note: This is basically the same documentation as the M2 one, as we expect the requirements and configuration to be the same._

Attraqt datasource support for Magento1 

---

changelog/front-commerce-3.1-2.27.mdx
docs/100-upgrade/_category_.yml
docs/100-upgrade/migration-guides/3.0-3.1.mdx
docs/100-upgrade/migration-guides/_category_.yml
docs/100-upgrade/release-notes.mdx
docs/migration/_category_.yml
versioned_docs/version-2.x/appendices/migration-guides/index.mdx
versioned_docs/version-2.x/appendices/release-notes.mdx

This PR does the following:
- update release notes for 2.27
- create new "Upgrade" section in the 3.x documentation, with Release notes and Migration guides
I decided to keep Migration guide pages separated for each versions in order to make them easier to manage.

3.1/2.27 release chores

---

versioned_docs/version-2.x/magento1/search-engine.mdx
versioned_docs/version-2.x/magento2/search-engine.mdx

This MR update our Attraqt recommendation example to feature the personalized recommendation support introduced in [!2888](https://gitlab.blackswift.cloud/front-commerce/front-commerce/-/merge_requests/2888).
[Magento1 preview](https://deploy-preview-815--heuristic-almeida-1a1f35.netlify.app/docs/2.x/magento1/search-engine#attraqt-recommendations-usage-example)
[Magento2 preview](https://deploy-preview-815--heuristic-almeida-1a1f35.netlify.app/docs/2.x/magento2/search-engine#attraqt-recommendations-usage-example) (both are the same)

Attraqt personalized recommendations support

---

versioned_docs/version-2.x/advanced/payments/adyen.mdx

This MR fixes a link in Adyen installation documentation page.
[Preview](https://github.com/front-commerce/developers.front-commerce.com/pull/820#issue-2034948493)

fix: Fixed link in Adyen documentation

---

docs/04-api-reference/front-commerce-core/defineExtension.mdx

This documents the `lifecycleHooks` in extensions config.
- Migrate Magic Button documentation
- Document registration for content metadata extractor

chore: document lifecycle hooks in extensions

---

blog/2023-advent-calendar/03-how-to-create-a-new-front-commerce-project.mdx
changelog/front-commerce-2.24.mdx
changelog/front-commerce-3.1-2.27.mdx
docs/01-get-started/installation.mdx
docs/02-guides/customize-the-styles.mdx
docs/02-guides/extend-the-graphql-schema.mdx
docs/02-guides/override-a-component.mdx
docs/02-guides/register-an-extension.mdx
docs/02-guides/translate-your-application.mdx
docs/03-extensions/algolia/how-to/magento1.mdx
docs/03-extensions/algolia/how-to/magento2.mdx
docs/03-extensions/algolia/how-to/standalone.mdx
docs/03-extensions/algolia/index.mdx
docs/03-extensions/algolia/reference/environment-variables.mdx
docs/03-extensions/contentful/index.mdx
docs/03-extensions/theme-chocolatine/reference/css-variables.mdx
docs/04-api-reference/front-commerce-core/defineExtension.mdx
docs/04-api-reference/front-commerce-remix/defineRemixExtension.mdx
docs/04-api-reference/front-commerce-remix/front-commerce-app.mdx
docs/100-upgrade/release-notes.mdx
docs/migration/deprecated-code-removal.mdx
docs/migration/manual-migration.mdx
docusaurus.config.js
src/theme/NotFound.tsx
static/_redirects
versions.json

This PR renames the `remixed` WIP documentation version to a `3.x` one, which becomes the default.
- it is now indexable
- all content has been updated to directly target the `3.x` versioned URL
- redirections were added to redirect WIP "/remixed/*" urls to their "/3.x/*" counterpart

Mark 3.x as official documentation and activate it by default

---

docs/03-extensions/adyen/_category_.yml
docs/03-extensions/adyen/how-to/_category_.yml
docs/03-extensions/adyen/how-to/front-commerce.mdx
docs/03-extensions/adyen/how-to/magento2.mdx
docs/03-extensions/adyen/index.mdx
docs/03-extensions/adyen/reference/_category_.yml
docs/03-extensions/adyen/reference/environment-variables.mdx

This MR adds the Adyen extension documentation in our v3.x docs. It mainly takes the v2.x documentation while also adding the v3-specific part about `front-commerce.config.ts`. It also does not include the Flashmessage configuration as this is not yet supported.
Related MRs:
- [!2929](https://gitlab.blackswift.cloud/front-commerce/front-commerce/-/merge_requests/2929)
- [!2938](https://gitlab.blackswift.cloud/front-commerce/front-commerce/-/merge_requests/2938)
- [!2940](https://gitlab.blackswift.cloud/front-commerce/front-commerce/-/merge_requests/2940)
- [!2947](https://gitlab.blackswift.cloud/front-commerce/front-commerce/-/merge_requests/2947)
Previews:
- [Main category](https://deploy-preview-825--heuristic-almeida-1a1f35.netlify.app/docs/3.x/extensions/adyen/)
- [As Front-Commerce …

Add Adyen extension documentation

---

blog/2023-advent-calendar/03-how-to-create-a-new-front-commerce-project.mdx
docs/01-get-started/loading-data-from-unified-graphql-schema.mdx
docs/02-guides/extend-the-graphql-schema.mdx
docs/03-extensions/algolia/how-to/standalone.mdx

This PR follows [!3037](https://gitlab.blackswift.cloud/front-commerce/front-commerce/-/merge_requests/3037) and updates all `skeleton/extensions` reference to `skeleton/example-extensions`.

Move extensions to example extension

---

docs/02-guides/configuration/01-add-a-configuration-provider.mdx
docs/02-guides/configuration/02-public-configuration.mdx
docs/02-guides/configuration/03-accessing-current-shop-configuration.mdx
docs/02-guides/configuration/_category_.yml
docs/03-extensions/algolia/how-to/standalone.mdx
docs/04-api-reference/front-commerce-core/config.mdx
docs/04-api-reference/front-commerce-core/defineExtension.mdx
docs/04-api-reference/front-commerce-remix/front-commerce-app.mdx
docs/100-upgrade/migration-guides/3.2-3.3.mdx
src/theme/MDXComponents.ts

- Documents changes in root.ts
- Documents deprecation of `getCurrentShopConfig`
- https://deploy-preview-834--heuristic-almeida-1a1f35.netlify.app/docs/3.x/upgrade/migration-guides/3.2-3.3
- https://deploy-preview-834--heuristic-almeida-1a1f35.netlify.app/docs/3.x/api-reference/front-commerce-core/config

chore: document simpler shop access

---

docs/100-upgrade/migration-guides/3.2-3.3.mdx

This PR updates the migration guide documented in #831 to be synced with latest changes (and codemods) added in https://gitlab.blackswift.cloud/front-commerce/front-commerce/-/merge_requests/3061 and https://gitlab.blackswift.cloud/front-commerce/front-commerce/-/merge_requests/3062
[:eyeglasses: **Preview**](https://deploy-preview-839--heuristic-almeida-1a1f35.netlify.app/docs/3.x/upgrade/migration-guides/3.2-3.3)

Update migration guide with latest implementation about automatic session commit

---

docs/04-api-reference/front-commerce-remix/health-check.mdx

This PR documents the `/__front-commerce/health` endpoint and its params.
[**PREVIEW**](https://deploy-preview-844--heuristic-almeida-1a1f35.netlify.app/docs/3.x/api-reference/front-commerce-remix/health-check)

Document the health check endpoint

---

docs/02-guides/override-a-component.mdx
docs/02-guides/translate-your-application.mdx

Removes `__dirname` from examples to be more iso with what happens when installing a front-commerce app

chore: remove __dirname examples

---

versioned_docs/version-2.x/prismic/resolver-cache.mdx

This MR fixes a typo in Prismic Cache documentation, that made a visual bug in the Prismic category page.
Before:
After:
Preview: https://deploy-preview-848--heuristic-almeida-1a1f35.netlify.app/docs/2.x/category/prismic

fix: Fixed 'description' medatada typo

---

docs/100-upgrade/migration-guides/3.2-3.3.mdx

This MR documents a forgotten migration guide following [FC-1802](https://linear.app/front-commerce/issue/FC-1802/styles-typography-fonts-etc-import-from-a-location-making-sense).
[Preview](https://deploy-preview-854--heuristic-almeida-1a1f35.netlify.app/docs/3.x/upgrade/migration-guides/3.2-3.3#theme-chocolatine-styles-refactor)

Added migration guide about theme chocolatine style refactor

---

docs/100-upgrade/migration-guides/3.0-3.1.mdx
docs/100-upgrade/migration-guides/3.1-3.2.mdx
docs/100-upgrade/migration-guides/3.2-3.3.mdx

This MR covers:
- Missing changes related to `publicConfig` usage
- Missing changes in `package.json` following the addition of a `post-install` script
Previews:
- [Remix entrypoints](https://deploy-preview-855--heuristic-almeida-1a1f35.netlify.app/docs/3.x/upgrade/migration-guides/3.2-3.3#remix-entrypoints)
- [post-install](https://deploy-preview-855--heuristic-almeida-1a1f35.netlify.app/docs/3.x/upgrade/migration-guides/3.2-3.3#front-commerce-post-install-script)

Added missing required manual change to 3.3 migration guide

---

docs/04-api-reference/front-commerce-core/makeCustomizableData.mdx

This MR adds a new document on how to use `makeCustomizableData`
[Preview](https://deploy-preview-851--heuristic-almeida-1a1f35.netlify.app/docs/3.x/api-reference/front-commerce-core/makeCustomizableData)

docs(core-reference): makeCustomizableData

---

docs/100-upgrade/migration-guides/3.0-3.1.mdx
docs/100-upgrade/migration-guides/3.1-3.2.mdx
docs/100-upgrade/migration-guides/3.2-3.3.mdx
docs/100-upgrade/migration-guides/3.3-3.4.mdx

This PR adds migration guide changes related to a fix on requisition lists made in [!3177](https://gitlab.blackswift.cloud/front-commerce/front-commerce/-/merge_requests/3177).
*Note for reviewers: The main change is the same in all migration guides (copy-pasted), the only change between guides is the "SinceVersion" version.*
Preview: https://deploy-preview-857--heuristic-almeida-1a1f35.netlify.app/docs/3.x/upgrade/migration-guides/3.3-3.4#requisition-list-related-theme-changes

chore: Added migration guide for requisition lists fix required changes

---

docs/03-extensions/payzen/how-to/front-commerce.mdx

This (small) PR fixes a (equally small) typo in Payzen's documentation.
[Preview](https://deploy-preview-858--heuristic-almeida-1a1f35.netlify.app/docs/3.x/extensions/payzen/how-to/front-commerce)
Before:
After:

chore: Fixed typo in Payzen documentation

---

docs/02-guides/extend-route-layout.mdx
docs/04-api-reference/front-commerce-remix/defineRemixExtension.mdx
docs/100-upgrade/migration-guides/3.3-3.4.mdx

This MR updates the docs followings changes regarding routes in `definedRemixExtension` API.

docs: Updated defineRemixExtension documentation along with the migration guide

---

docs/100-upgrade/migration-guides/3.3-3.4.mdx

This PR adds simple docs for migrating from `unstable_module` from `module`
https://deploy-preview-860--heuristic-almeida-1a1f35.netlify.app/docs/3.x/upgrade/migration-guides/3.3-3.4#from-graphqlunstable_module-to-graphqlmodule

docs(migration): migrate from unstable_modules from modules

---

docs/03-extensions/stripe/_category_.yml
docs/03-extensions/stripe/how-to/_category_.yml
docs/03-extensions/stripe/how-to/apple-pay-google-pay.mdx
docs/03-extensions/stripe/how-to/customize-data.mdx
docs/03-extensions/stripe/how-to/disable-automatic-capture.mdx
docs/03-extensions/stripe/index.mdx
docs/03-extensions/stripe/reference/_category_.yml
docs/03-extensions/stripe/reference/environment-variables.mdx

This PR implement documentation for Stripe
[Preview](https://deploy-preview-863--heuristic-almeida-1a1f35.netlify.app/docs/3.x/extensions/stripe/)

docs(stripe): adding docs for stripe

---

docs/03-extensions/stripe/index.mdx

This MR documents changes from [!3265](https://gitlab.blackswift.cloud/front-commerce/front-commerce/-/merge_requests/3265) about adding `flavors` to Stripe extension.
[Preview](https://deploy-preview-866--heuristic-almeida-1a1f35.netlify.app/docs/3.x/extensions/stripe/)

Stripe extension flavors

---

docs/03-extensions/payzen/how-to/front-commerce.mdx

This adds a missing step in Payzen configuration for Magento1

chore(docs): update Payzen docs for M1

---

docs/03-extensions/paypal/_category_.yml
docs/03-extensions/paypal/how-to/_category_.yml
docs/03-extensions/paypal/index.mdx
docs/03-extensions/paypal/reference/_category_.yml
docs/03-extensions/paypal/reference/environment-variables.mdx

This MR documents the PayPal extension installation and configuration, following [!3272](https://gitlab.blackswift.cloud/front-commerce/front-commerce/-/merge_requests/3272).
[Preview](https://deploy-preview-870--heuristic-almeida-1a1f35.netlify.app/docs/3.x/extensions/paypal/)

docs: Documented PayPal extension

---

docs/100-upgrade/migration-guides/3.3-3.4.mdx

This MR documents the removal of `remix-pwa` packages in the migration guide, as well as the requirement to install `workbox-window`.
[Preview](https://deploy-preview-875--heuristic-almeida-1a1f35.netlify.app/docs/3.x/upgrade/migration-guides/3.3-3.4#removal-of-remix-pwa-in-favor-of-vite-pwa)

docs(migration): Documented removal of remix-pwa in migration guide

---

docs/100-upgrade/migration-guides/3.3-3.4.mdx
docs/migration/manual-migration.mdx

This MR adds some details about the Vite migration and `pnpm` instructions required when migrating an existing project.
**[Preview](https://deploy-preview-876--heuristic-almeida-1a1f35.netlify.app/docs/3.x/upgrade/migration-guides/3.3-3.4)**

3.4 migration guide: make vite installation more obvious

---

docs/03-extensions/theme-chocolatine/how-to/customize-the-offline-page.mdx
docs/100-upgrade/migration-guides/3.3-3.4.mdx
docs/migration/manual-migration.mdx

[Related MR](https://gitlab.blackswift.cloud/front-commerce/front-commerce/-/merge_requests/3282).
This MR documents the Offline page migration to v3.
- How to customize the offline page
- `FRONT_COMMERCE_DISABLE_OFFLINE_MODE` removal (migration guide)
[Preview how-to](https://deploy-preview-872--heuristic-almeida-1a1f35.netlify.app/docs/3.x/extensions/theme-chocolatine/how-to/customize-the-offline-page)
[Preview migration guide](https://deploy-preview-872--heuristic-almeida-1a1f35.netlify.app/docs/3.x/migration/manual-migration#front-commerce)

docs: Documented Offline page migration

---

versioned_docs/version-2.x/magento2/installation.mdx

This document an info about Magento2 token expiration setup from Magento 2.4.4.
From 2.4.4 Magento2 is using JWT token to process customer authentication, this docs add infos about raising session lifetime in this case

docs(magento2): adding note about token durations from Magento2.4.4

---

docs/100-upgrade/migration-guides/3.3-3.4.mdx
docs/migration/manual-migration.mdx

This MR adds missing migrations point to take into account while migrating to FC 3.4.
Also fixed a typo in the ESM paragraph.
[Preview](https://deploy-preview-877--heuristic-almeida-1a1f35.netlify.app/docs/3.x/migration/manual-migration#transitioning-to-esm)

docs: Update migration guide about missing ESM migration points

---

docs/02-guides/maintenance-mode.mdx
docs/100-upgrade/migration-guides/3.3-3.4.mdx

Updates the documentation related to the maintenance mode, and documents the required diff for root.tsx
- https://deploy-preview-886--heuristic-almeida-1a1f35.netlify.app/docs/3.x/guides/maintenance-mode
- https://deploy-preview-886--heuristic-almeida-1a1f35.netlify.app/docs/3.x/upgrade/migration-guides/3.3-3.4#remix-entrypoints

document migration guide for remix entry files and maintenance mode page customization

---

docs/02-guides/pwa-setup.mdx
docs/100-upgrade/migration-guides/3.3-3.4.mdx

This MR follows [!3295](https://gitlab.blackswift.cloud/front-commerce/front-commerce/-/merge_requests/3295) and documents the changes made to `entry.worker.ts` following the addition of the Offline page.
[Preview ](https://gitlab.blackswift.cloud/front-commerce/front-commerce/-/blob/main/packages/remix/config/defineFrontCommerceRoutes.ts#L248)

docs: Documented changes on entry.worker.ts following the offline page support

---

docs/03-extensions/contentful/reference/_category_.yml
docs/03-extensions/contentful/reference/api.mdx
docs/03-extensions/contentful/reference/environment-variables.mdx
static/_redirects

This MR refactors the "Reference" section of our Contentful doc to feature a new "Environment variables" section for listing all variables used by the Contentful extension.
[Preview ](https://deploy-preview-891--heuristic-almeida-1a1f35.netlify.app/docs/3.x/extensions/contentful/reference/environment-variables)

docs: Documented the list of environment variables used by Contentful extension

---

docs/02-guides/extend-vite-configuration/_category_.yml
docs/02-guides/extend-vite-configuration/tailwind.mdx

This introduce a guide to setup tailwind in a front-commerce project
https://deploy-preview-894--heuristic-almeida-1a1f35.netlify.app/docs/3.x/guides/extend-vite-configuration/tailwind

Fc 2127 doc examples of tailwind

---

docs/02-guides/extend-vite-configuration/mdx.mdx

This adds doc to use MDX in a Front-Commerce project
https://deploy-preview-899--heuristic-almeida-1a1f35.netlify.app/docs/3.x/guides/extend-vite-configuration/mdx

docs(mdx): adding docs for mdx

---

docs/100-upgrade/migration-guides/3.0-3.1.mdx
docs/100-upgrade/migration-guides/3.1-3.2.mdx
docs/100-upgrade/migration-guides/3.2-3.3.mdx
docs/100-upgrade/migration-guides/3.4-3.5.mdx

This adds a migration guide about new configurations for 3.5 version
https://deploy-preview-902--heuristic-almeida-1a1f35.netlify.app/docs/3.x/upgrade/migration-guides/3.4-3.5

docs(config): adding documentation about new configuration

---

versioned_docs/version-2.x/advanced/payments/stripe.mdx
versioned_docs/version-2.x/appendices/migration-guides/index.mdx

This MR follows [!3436](https://gitlab.blackswift.cloud/front-commerce/front-commerce/-/merge_requests/3436) and documents necessary changes for Stripe to work with IPNs.
- [Migration Guide](https://deploy-preview-905--heuristic-almeida-1a1f35.netlify.app/docs/2.x/appendices/migration-guides/#2290---2300)
- [Stripe documentation](https://deploy-preview-905--heuristic-almeida-1a1f35.netlify.app/docs/2.x/advanced/payments/stripe#extra-steps-for-magento2--magento2-b2b)

Stripe as IPN documentation

---

docs/02-guides/analytics/_category_.yml
docs/02-guides/analytics/addingwell.mdx
versioned_docs/version-2.x/advanced/analytics/plugins.mdx

This adds documentation about Addingwell usage
[V2](https://deploy-preview-903--heuristic-almeida-1a1f35.netlify.app/docs/2.x/advanced/analytics/server-side-tagging-tracking)
[V3](https://deploy-preview-903--heuristic-almeida-1a1f35.netlify.app/docs/3.x/guides/analytics/addingwell)

docs(analytics): addingwell support

---

docs/02-guides/dynamic-routing.mdx
docs/migration/manual-migration.mdx

This pull request adds documentation for batching and prioritizing URL matchers in the codebase. It explains how to set the `batchOrder` and `priority` fields in the `matcherOptions` object to control the order of execution for multiple URL matchers. Additionally, it includes an example of the desired order of execution for a list of URL matchers. 
This also includes better migration guide for the deprecated page loader

Dynamic Routing documentation updates

---

docs/04-api-reference/front-commerce-remix/seo.mdx

This pull request adds documentation for the Remix SEO API. It includes information on the `generateSitemap` and `generateRobotsTxt` functions, along with examples of how to use them.

Document Remix SEO API

---

docs/100-upgrade/migration-guides/3.5-3.6.mdx

Added detailed documentation for changes introduced in the automated migration script for version 3.6.0. This includes:
- Adding `pazyen` flavor to extension options.
- Replacing `limitRateByClientIp` with `limitRateByGraphQLResolver`.
- Renaming mutation types with new conventions.
Also included examples and links to relevant tests and ADRs. Updated the migration guide to reflect these changes and added an info section about the default flavor for the Payzen module.

chore: update migration guide for 3.6

---

docs/100-upgrade/migration-guides/3.5-3.6.mdx

Documents react canary version update

chore: document react 18.3 canary update

---

docs/100-upgrade/migration-guides/3.5-3.6.mdx
versioned_docs/version-2.x/appendices/migration-guides/index.mdx

Preview: 
- [3.6](https://deploy-preview-925--heuristic-almeida-1a1f35.netlify.app/docs/3.x/upgrade/migration-guides/3.5-3.6#server-timings)
- [2.31.0](https://deploy-preview-925--heuristic-almeida-1a1f35.netlify.app/docs/2.x/appendices/migration-guides/)

Migration guides: fix typos in the 3.6 guide, and add a section for 2.31.0

---

docs/03-extensions/adyen/how-to/front-commerce.mdx

This adds a a note about store configuration needed for Adyen payment to work properly

docs(adyen): adding note about store configuration needed for adyen

---

docs/100-upgrade/migration-guides/3.5-3.6.mdx

So developers can use the latest version.
Because using an old `pnpm` version on the latest FC Cloud versions can cause issues with FC 3.6.0.
FC supports pnpm 9 since 3.6 ([MR!3497](https://gitlab.blackswift.cloud/front-commerce/front-commerce/-/merge_requests/3497)).
This PR adds a note in the migration guide so integrators can update their local version.
[**Migration guide**](https://deploy-preview-931--heuristic-almeida-1a1f35.netlify.app/docs/3.x/upgrade/migration-guides/3.5-3.6#use-the-latest-pnpm-version)

3.6: Document the `pnpm` version update

---

docs/03-extensions/akamai-image-manager/index.mdx

This PR adds a page for the `@front-commerce/akamai-image-manager` extension.
We never added it before.
It contains the standard install procedure and configuration instructions ported from the 2.x documentation.
**[PREVIEW](https://deploy-preview-934--heuristic-almeida-1a1f35.netlify.app/docs/3.x/extensions/akamai-image-manager/)**

Document Akamai Image Manager extension

---

docs/03-extensions/magento2/index.mdx
versioned_docs/version-2.x/magento2/installation.mdx

**_[bugsfc #52003 Magento 2.4.6: Les produits "Grouped" ne se chargent pas](https://tuleap.lundimatin.biz/plugins/tracker/?aid=52003)_**
This MR documents an issue in Magento 2.4.6 that causes grouped product options to be `null` if the related products are set to `Not Visible Individually`.
Previews:
- [V3](https://github.com/front-commerce/developers.front-commerce.com/pull/949)
- [V2](https://deploy-preview-949--heuristic-almeida-1a1f35.netlify.app/docs/2.x/magento2/installation#known-issues)

docs: Documented magento 2.4.6 issue with grouped products

---

docs/100-upgrade/migration-guides/3.7-3.8.mdx

A new migration guide has been added to the documentation for upgrading a project from Front-Commerce version 3.7 to 3.8. This guide includes instructions for updating dependencies, using an automated migration tool, and details about additional SEO meta data fields for Category and Product schemas. The new fields include `meta_robots`, `meta_product_retailer_item_id`, and `meta_product_availability`. Links to full diffs and relevant code sections are also provided.

Add migration guide for Front-Commerce 3.7 to 3.8 with SEO meta additions

---

docs/100-upgrade/migration-guides/3.7-3.8.mdx

This PR documents a change related to a fix made on `/media` routes.
[Related MR](https://gitlab.blackswift.cloud/front-commerce/front-commerce/-/merge_requests/3667)

docs: Documented changes related to the fix on /media routes

---

docs/100-upgrade/migration-guides/3.7-3.8.mdx

🎟️ [bugsfc #51681](https://tuleap.lundimatin.biz/plugins/tracker/?aid=51681)
https://deploy-preview-959--heuristic-almeida-1a1f35.netlify.app/docs/3.x/upgrade/migration-guides/3.7-3.8#front-commerceremix-no-longer-depends-on-opentelemetryinstrumentation

chore: document metrics and server.mjs changes

---

docs/03-extensions/payzen/index.mdx
versioned_docs/version-2.x/advanced/payments/payzen.mdx

_Context: https://app.intercom.com/a/inbox/ehgzoeah/inbox/conversation/188350900001560?view=List_
Because in staging environments protected with Basic auth, notifications can be blocked and will lead to incorrect behaviors.
This patch documents Lyra's IP addresses to allow in a protected environment.
Since this "Configure your environment" section started to grow, I added sub-sections.
- [2.x documentation page](https://deploy-preview-963--heuristic-almeida-1a1f35.netlify.app/docs/2.x/advanced/payments/payzen#configure-your-environment)
- [3.x documentation page](https://deploy-preview-963--heuristic-almeida-1a1f35.netlify.app/docs/3.x/extensions/payzen/#configure-your-environment)

Document Lyra's IP addresses to allow on protected environments

---

docs/02-guides/error-handling-for-routes.mdx

The documentation for error handling in routes has been updated to include a new section on customizing meta tags for error pages. This section provides guidance on how to override the `generateAppRouteErrorMeta.ts` to add custom meta tags. It includes instructions for creating a new meta tag generator and adding custom meta tags, as well as information on the default meta tags provided by Front-Commerce for common status codes. This enhancement is available from version 3.9.
https://deploy-preview-965--heuristic-almeida-1a1f35.netlify.app/docs/3.x/guides/error-handling-for-routes#customizing-meta-tags

docs: document customization of route error meta tags

---

docs/100-upgrade/migration-guides/3.8-3.9.mdx

A new migration guide has been added to assist users in upgrading their projects from Front-Commerce version 3.8 to 3.9. The guide includes instructions for updating dependencies, utilizing an automated migration tool, and performing manual migrations. It provides specific details on updating Remix entrypoints, including a code snippet for changes in the `app/root.tsx` file. 
This might not be required depending on https://gitlab.blackswift.cloud/front-commerce/front-commerce/-/merge_requests/3703

Add Migration Guide for Upgrading from Front-Commerce 3.8 to 3.9

---

docs/02-guides/maintenance-mode/automatic-detection-with-service-health-checks.mdx
docs/04-api-reference/front-commerce-core/create-resized-image-response.mdx

This PR improves some content that appeared to be unclear (from user feedback)
- Clarify the image resizing example about duration
- Fix return value for the healtcheck service example (logic was incorrect)

Improve unclear documentation

---

docs/04-api-reference/front-commerce-core/react.mdx

This PR documents the optional "fallback" parameter to `useExtensionComponentMap` following some changes in [!3803](https://gitlab.blackswift.cloud/front-commerce/front-commerce/-/merge_requests/3803).

docs: documents changes on useExtensionComponentMap

---

docs/02-guides/analytics/getting-started.mdx
docs/100-upgrade/migration-guides/3.8-3.9.mdx
versioned_docs/version-2.x/advanced/analytics/getting-started.mdx
versioned_docs/version-2.x/appendices/migration-guides/index.mdx

documents [🎟️ FC-3021](https://docs.google.com/document/d/1axv-l-X-LCDj82msnbqCGOPOsKbJ7iRDZXGpTsgE78U/edit?tab=t.0)
- 3.x
- [Migration Guide](https://deploy-preview-996--heuristic-almeida-1a1f35.netlify.app/docs/3.x/upgrade/migration-guides/3.8-3.9#google-consent-v2-support)
- [Granular Consent Updates Guide](https://deploy-preview-996--heuristic-almeida-1a1f35.netlify.app/docs/3.x/upgrade/migration-guides/3.8-3.9#google-consent-v2-support)
- 2.x
- [Migration Guide](https://deploy-preview-996--heuristic-almeida-1a1f35.netlify.app/docs/2.x/appendices/migration-guides/#google-consent-v2-support)
- [Granular Consent Updates Guide](https://deploy-preview-996--heuristic-almeida-1a1f35.netlify.app/docs/2.x/advanced/analytics/getting-started#granular-consent-updates)

chore: document consent options and migration guide for google

---

docs/100-upgrade/migration-guides/3.7-3.8.mdx
docs/100-upgrade/migration-guides/3.8-3.9.mdx

[🎟️ FC-3020](https://docs.google.com/document/d/1knQ2AlZJ80kKCdp5tMvrpfZ3_oO6Lf16VA13ZIb5A7E/edit?tab=t.0)
This documents the update required to use the `RootErrorBoundary`
Since we forgot to document it in `3.8.x` update, I documented this in both `3.8.x` and `3.9.x`
I also removed the section for the `rootLoaderContext` since this was never documented, and I don't believe projects would have applied this temporary change.
- [3.8 -> 3.9](https://deploy-preview-1001--heuristic-almeida-1a1f35.netlify.app/docs/3.x/upgrade/migration-guides/3.8-3.9#root-error-boundary) Migration Guide
- [3.7 -> 3.8](https://deploy-preview-1001--heuristic-almeida-1a1f35.netlify.app/docs/3.x/upgrade/migration-guides/3.7-3.8#root-error-boundary) Migration Guide

chore: document root error boundary updates

---

docs/02-guides/extension-features/feature-flags.mdx
docs/04-api-reference/front-commerce-core/extension-features.mdx
docs/04-api-reference/front-commerce-core/react.mdx

This PR implement documentation about feature flags
[Preview link](https://deploy-preview-1003--heuristic-almeida-1a1f35.netlify.app/docs/3.x/guides/extension-features/feature-flags)

feat(feature-flags): add simple documentation about feature flags

---

docs/02-guides/extend-vite-configuration/remix-development-tools.mdx

This implement a small documentation about setting up Remix Development Tools in Front-Commerce
Add a quickstart guide
[Preview link](https://deploy-preview-1010--heuristic-almeida-1a1f35.netlify.app/docs/3.x/guides/extend-vite-configuration/remix-development-tools)

chore: add docs about remix-dev-tools

---

docs/02-guides/display-a-map.mdx
docs/03-extensions/google-maps/index.mdx
docs/03-extensions/leaflet/index.mdx
docs/03-extensions/theme-chocolatine/reference/features.mdx
docs/03-extensions/theme-chocolatine/reference/maps.mdx
docs/100-upgrade/migration-guides/3.9-3.10.mdx

This MR follows [!3852](https://gitlab.blackswift.cloud/front-commerce/front-commerce/-/merge_requests/3852), [!3855](https://gitlab.blackswift.cloud/front-commerce/front-commerce/-/merge_requests/3855) and [!3862](https://gitlab.blackswift.cloud/front-commerce/front-commerce/-/merge_requests/3862), and documents changes made related to shipping method additional data collection:
- New `features`: `shippingMethodAdditionalData` and `maps`
- Also documented the related migration guide for this.
- Added `Leaflet` package
- Added `Google Maps` package

docs: Documentated Maps extensions and shipping methods changes
